"""Package smoke self-test: learn skill-proposal review and apply-plan generation."""
from __future__ import annotations

import json

from pathlib import Path
from smoke_assertions import (
    EXPECTED_ROUTE_ID,
    expect_self_test_failure,
)
from smoke_domains.package_learning_agent_backlog import assert_agent_backlog_report_json
from smoke_domains.package_learning_agent_backlog_reports import (
    assert_agent_backlog_no_command_json,
    assert_agent_backlog_report_human,
    assert_agent_backlog_report_markdown,
)
from smoke_domains.package_learning_skill_proposal import assert_skill_proposal_report_json
from smoke_domains.package_learning_skill_proposal_apply import assert_skill_proposal_apply_plan_json
from smoke_domains.package_learning_skill_proposal_review import (
    assert_skill_proposal_review_check_json,
    assert_skill_proposal_review_check_markdown,
    assert_skill_proposal_review_json,
)


def _self_test_learn_proposal_review(agent_backlog_refresh_command, context, learn_agent_backlog_cmd, learning_agent_backlog_payload, learning_profile_path, learning_usage_path, refresh_reason_drift_payload, tmp):
    """Package smoke self-test: learn skill-proposal review contracts."""
    expect_self_test_failure(
        lambda: assert_agent_backlog_no_command_json(
            json.dumps(refresh_reason_drift_payload),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="no-command learn agent backlog JSON should preserve optional refresh-only runbook reason",
        scope="package smoke",
    )
    assert_agent_backlog_report_human(
        "\n".join([
            "design-ai learn",
            "Agent development backlog",
            f"Signal source: {Path(tmp)}",
            "Backlog actions:",
            "Action plan:",
            "safety summary:",
            "execution queue:",
            "next action:",
            "next command:",
            "next command policy:",
            "queue order:",
            "command manifest:",
            "command effects:",
            "command effect review:",
            "command effect gate phases:",
            "command effect gate runbook:",
            "command effect gates:",
            "operator runbook:",
            "operator next command:",
            "refresh:",
            "safety: read-only",
            "requires mutation review: no",
            "design-ai learn --propose-skills --json",
            "Privacy: agent backlog is read-only",
        ]),
        context=context,
        cmd=learn_agent_backlog_cmd,
    )
    assert_agent_backlog_report_markdown(
        "\n".join([
            "# Agent Development Backlog Report",
            "",
            f"- Learning file: {learning_profile_path}",
            f"- Usage file: {learning_usage_path}",
            "## Summary",
            "## Signal Readiness",
            "- Required ready: yes",
            "- Required checks: 4/4",
            "- Blocking checks: 0",
            "- Optional gaps: 0",
            "Readiness check index:",
            "- Required ids: learning-profile, eval-signals, workspace-readiness, agent-development",
            "- Optional ids: usage-sidecar, check-capture",
            "- Status index: learning-profile=pass, usage-sidecar=pass, eval-signals=pass, check-capture=pass, workspace-readiness=pass, agent-development=pass",
            "- Required index: learning-profile=yes, usage-sidecar=no, eval-signals=yes, check-capture=no, workspace-readiness=yes, agent-development=yes",
            "- Status counts: pass=6, info=0, warn=0, fail=0, missing=0, template=0, unknown=0",
            "- Required status counts: pass=4, info=0, warn=0, fail=0, missing=0, template=0, unknown=0",
            "- Optional status counts: pass=2, info=0, warn=0, fail=0, missing=0, template=0, unknown=0",
            "Readiness checks:",
            "- check-capture [optional] pass: Profile includes 1 check-capture learning entry.",
            "- agent-development [required] pass: Agent backlog has 1 action(s): 0 P0, 0 P1, 1 P2, 0 P3.",
            "## Backlog Actions",
            "design-ai learn --propose-skills --json",
            "## Action Plan",
            "Safety summary:",
            "- Read-only: 1",
            "- Writes local file: 0",
            "- Mutates local state: 0",
            "Execution queue:",
            "- Preview/read-only commands: 1",
            "- Local file-write review commands: 0",
            "- Local mutation review commands: 0",
            "- Ordered commands: 1",
            "- Command manifest entries: 1",
            "- Command effect targets: output 0, profile 0, usage 0, mutation flags 0",
            "- Command effect review: No command target or mutation flag exposure detected.",
            "- Command effect gate phases: refresh (1/1 required)",
            "- Command effect gate runbook: before 0, after 0, refresh 1",
            "- Command effect gates:",
            "refresh: Refresh focused agent backlog after review",
            agent_backlog_refresh_command,
            "- Operator runbook: 4 stage(s), 2 command(s), 2 required",
            "- Operator next command: execute: `design-ai learn --propose-skills --json`",
            "- Operator handoff state: ready; ready yes; can run without review yes; refresh required",
            "- Recommended next action: agent-skill-proposal-preview",
            "- Recommended next command policy: preview-only",
            "Recommended next command:",
            "Queue order:",
            "1. agent-skill-proposal-preview (read-only, preview-only)",
            "Command manifest:",
            "1. agent-skill-proposal-preview - preview-only (read-only)",
            "- Command safety: read-only",
            "- Writes local files: no",
            "- Mutates local state: no",
            "- Requires mutation review: no",
            agent_backlog_refresh_command,
            "## Follow-Up Commands",
            "design-ai learn --signals --from-file . --json",
            "## Privacy And Boundaries",
            "- Mutates learning profile: no",
            "- Mutates skill files: no",
            "- Calls external AI APIs: no",
            "This report is read-only evidence; it does not mutate learning profiles, usage sidecars, eval files, skill files, or target repositories.",
        ]),
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        context=context,
        cmd=[*learn_agent_backlog_cmd[:-1], "--report"],
    )
    expect_self_test_failure(
        lambda: assert_agent_backlog_report_json(
            json.dumps({
                **learning_agent_backlog_payload,
                "counts": {
                    **learning_agent_backlog_payload["counts"],
                    "evalSignals": 0,
                },
            }),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="learn agent backlog JSON should include focused backlog counts",
        scope="package smoke",
    )
    expect_self_test_failure(
        lambda: assert_agent_backlog_report_json(
            json.dumps({
                **learning_agent_backlog_payload,
                "actionPlan": {
                    **learning_agent_backlog_payload["actionPlan"],
                    "steps": [],
                },
            }),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="learn agent backlog JSON should include executable action plan steps and verification",
        scope="package smoke",
    )
    missing_safety_summary_payload = json.loads(json.dumps(learning_agent_backlog_payload))
    missing_safety_summary_payload["actionPlan"].pop("safetySummary", None)
    expect_self_test_failure(
        lambda: assert_agent_backlog_report_json(
            json.dumps(missing_safety_summary_payload),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="learn agent backlog JSON should include executable action plan steps and verification",
        scope="package smoke",
    )
    missing_execution_queue_payload = json.loads(json.dumps(learning_agent_backlog_payload))
    missing_execution_queue_payload["actionPlan"].pop("executionQueue", None)
    expect_self_test_failure(
        lambda: assert_agent_backlog_report_json(
            json.dumps(missing_execution_queue_payload),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="learn agent backlog JSON should include executable action plan steps and verification",
        scope="package smoke",
    )
    unsafe_action_plan_payload = json.loads(json.dumps(learning_agent_backlog_payload))
    unsafe_action_plan_payload["actionPlan"]["steps"][0].pop("commandSafety", None)
    expect_self_test_failure(
        lambda: assert_agent_backlog_report_json(
            json.dumps(unsafe_action_plan_payload),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="learn agent backlog JSON should include executable action plan steps and verification",
        scope="package smoke",
    )
    expect_self_test_failure(
        lambda: assert_agent_backlog_report_json(
            json.dumps({
                **learning_agent_backlog_payload,
                "privacy": {
                    **learning_agent_backlog_payload["privacy"],
                    "mutatesSkillFiles": True,
                },
            }),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="learn agent backlog JSON should keep read-only local privacy boundaries",
        scope="package smoke",
    )
    expect_self_test_failure(
        lambda: assert_agent_backlog_report_markdown(
            "\n".join([
                "# Agent Development Backlog Report",
                f"- Learning file: {learning_profile_path}",
                f"- Usage file: {learning_usage_path}",
                "## Summary",
                "## Signal Readiness",
                "- Required ready: yes",
                "- Required checks: 4/4",
                "- Blocking checks: 0",
                "- Optional gaps: 0",
                "Readiness check index:",
                "- Required ids: learning-profile, eval-signals, workspace-readiness, agent-development",
                "- Optional ids: usage-sidecar, check-capture",
                "- Status index: learning-profile=pass, usage-sidecar=pass, eval-signals=pass, check-capture=pass, workspace-readiness=pass, agent-development=pass",
                "- Required index: learning-profile=yes, usage-sidecar=no, eval-signals=yes, check-capture=no, workspace-readiness=yes, agent-development=yes",
                "- Status counts: pass=6, info=0, warn=0, fail=0, missing=0, template=0, unknown=0",
                "- Required status counts: pass=4, info=0, warn=0, fail=0, missing=0, template=0, unknown=0",
                "- Optional status counts: pass=2, info=0, warn=0, fail=0, missing=0, template=0, unknown=0",
                "Readiness checks:",
                "- check-capture [optional] pass: Profile includes 1 check-capture learning entry.",
                "- agent-development [required] pass: Agent backlog has 1 action(s): 0 P0, 0 P1, 1 P2, 0 P3.",
                "## Backlog Actions",
                "design-ai learn --propose-skills --json",
                "## Action Plan",
                "Safety summary:",
                "- Read-only: 1",
                "- Writes local file: 0",
                "- Mutates local state: 0",
                "Execution queue:",
                "- Preview/read-only commands: 1",
                "- Local file-write review commands: 0",
                "- Local mutation review commands: 0",
                "- Ordered commands: 1",
                "- Command manifest entries: 1",
                "- Command effect targets: output 0, profile 0, usage 0, mutation flags 0",
                "- Command effect review: No command target or mutation flag exposure detected.",
                "- Command effect gate phases: refresh (1/1 required)",
                "- Command effect gate runbook: before 0, after 0, refresh 1",
                "- Command effect gates:",
                "refresh: Refresh focused agent backlog after review",
                agent_backlog_refresh_command,
                "- Operator runbook: 4 stage(s), 2 command(s), 2 required",
                "- Operator next command: execute: `design-ai learn --propose-skills --json`",
                "- Operator handoff state: ready; ready yes; can run without review yes; refresh required",
                "- Recommended next action: agent-skill-proposal-preview",
                "- Recommended next command policy: preview-only",
                "Recommended next command:",
                "Queue order:",
                "1. agent-skill-proposal-preview (read-only, preview-only)",
                "Command manifest:",
                "1. agent-skill-proposal-preview - preview-only (read-only)",
                "- Command safety: read-only",
                "- Writes local files: no",
                "- Mutates local state: no",
                "- Requires mutation review: no",
                agent_backlog_refresh_command,
                "## Follow-Up Commands",
                "design-ai learn --signals --from-file . --json",
                "## Privacy And Boundaries",
                "- Mutates learning profile: no",
                "- Mutates skill files: yes",
                "- Calls external AI APIs: no",
                "This report is read-only evidence",
            ]),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=[*learn_agent_backlog_cmd[:-1], "--report"],
        ),
        expected="learn agent backlog Markdown report missing '- Mutates skill files: no'",
        scope="package smoke",
    )

    learn_skill_proposals_cmd = [
        "design-ai",
        "learn",
        "--propose-skills",
        "--file",
        str(learning_profile_path),
        "--usage-file",
        str(learning_usage_path),
        "--from-file",
        str(Path(tmp)),
        "--json",
    ]
    learning_skill_proposal_payload = {
        "version": 1,
        "generatedAt": "2026-06-02T00:00:00.000Z",
        "file": str(learning_profile_path),
        "usageFile": str(learning_usage_path),
        "signalSource": str(Path(tmp)),
        "dryRun": True,
        "applied": False,
        "minEvidenceCount": 2,
        "checkCaptureCount": 2,
        "candidateCount": 1,
        "count": 1,
        "proposalCount": 1,
        "skippedCount": 0,
        "pendingReviewCount": 1,
        "reviewedCount": 0,
        "reviewFile": "",
        "review": {
            "file": "",
            "exists": False,
            "status": "not-configured",
            "decisionCount": 0,
            "matchedCount": 0,
            "staleCount": 0,
            "pendingCount": 1,
            "acceptedCount": 0,
            "rejectedCount": 0,
            "appliedCount": 0,
            "deferredCount": 0,
            "clearedCount": 0,
            "warnings": [],
        },
        "status": "warn",
        "signalStatus": "pass",
        "proposals": [
            {
                "id": "skill-proposal-component-spec-writer-abcdef1234",
                "candidateSkill": "component-spec-writer",
                "candidateSkillPath": "skills/component-spec-writer/SKILL.md",
                "title": "Update skills/component-spec-writer/SKILL.md for repeated accessibility check captures",
                "riskLevel": "low",
                "reviewStatus": "pending",
                "reviewClearsStrict": False,
                "category": "accessibility",
                "routeIds": [EXPECTED_ROUTE_ID],
                "sourceIssueCount": 2,
                "proposedInstructionDelta": "Add a pre-handoff accessibility checkpoint.",
                "verificationCommand": f"node cli/bin/design-ai.mjs check --examples --route {EXPECTED_ROUTE_ID} --limit 1 --strict --json",
                "evidenceSources": [
                    {
                        "kind": "check-capture",
                        "entryId": "learn-skill-proposal-a",
                        "category": "accessibility",
                        "source": f"check:{EXPECTED_ROUTE_ID}",
                        "routeId": EXPECTED_ROUTE_ID,
                        "textPreview": "Improve future outputs by addressing Keyboard and focus behavior.",
                    },
                    {
                        "kind": "check-capture",
                        "entryId": "learn-skill-proposal-b",
                        "category": "accessibility",
                        "source": f"check:{EXPECTED_ROUTE_ID}",
                        "routeId": EXPECTED_ROUTE_ID,
                        "textPreview": "Improve future outputs by addressing Screen reader behavior.",
                    },
                ],
            },
        ],
        "skipped": [],
        "recommendations": [],
        "privacy": {
            "mutatesProfile": False,
            "mutatesSkillFiles": False,
            "callsExternalAiApis": False,
            "storesRawBriefText": False,
            "exposesEntryTextPreview": True,
        },
    }
    assert_skill_proposal_report_json(
        json.dumps(learning_skill_proposal_payload),
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        context=context,
        cmd=learn_skill_proposals_cmd,
    )
    learning_skill_proposal_review_path = learning_profile_path.with_name("skill-proposals.review.json")
    assert_skill_proposal_review_json(
        json.dumps({
            **learning_skill_proposal_payload,
            "status": "pass",
            "pendingReviewCount": 0,
            "reviewedCount": 1,
            "reviewFile": str(learning_skill_proposal_review_path),
            "review": {
                **learning_skill_proposal_payload["review"],
                "file": str(learning_skill_proposal_review_path),
                "exists": True,
                "status": "pass",
                "decisionCount": 1,
                "matchedCount": 1,
                "pendingCount": 0,
                "appliedCount": 1,
                "clearedCount": 1,
            },
            "proposals": [
                {
                    **learning_skill_proposal_payload["proposals"][0],
                    "reviewStatus": "applied",
                    "reviewClearsStrict": True,
                    "reviewDecision": {
                        "proposalId": "skill-proposal-component-spec-writer-abcdef1234",
                        "status": "applied",
                        "reviewedAt": "2026-06-11T00:00:00.000Z",
                        "reviewer": "package-smoke",
                        "note": "Instruction delta manually applied.",
                    },
                },
            ],
        }),
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        review_path=learning_skill_proposal_review_path,
        context=context,
        cmd=[*learn_skill_proposals_cmd[:-1], "--review-file", str(learning_skill_proposal_review_path), "--json"],
    )
    learning_skill_proposal_review_check_payload = {
        "version": 1,
        "kind": "skill-proposal-review-check",
        "generatedAt": "2026-06-11T00:05:00.000Z",
        "file": str(learning_profile_path),
        "usageFile": str(learning_usage_path),
        "signalSource": str(Path(tmp)),
        "reviewFile": str(learning_skill_proposal_review_path),
        "status": "pass",
        "proposalStatus": "pass",
        "signalStatus": "pass",
        "proposalCount": 1,
        "pendingReviewCount": 0,
        "reviewedCount": 1,
        "review": {
            **learning_skill_proposal_payload["review"],
            "file": str(learning_skill_proposal_review_path),
            "exists": True,
            "status": "pass",
            "decisionCount": 1,
            "matchedCount": 1,
            "pendingCount": 0,
            "appliedCount": 1,
            "clearedCount": 1,
        },
        "summary": {
            "status": "pass",
            "failures": 0,
            "warnings": 0,
            "passes": 5,
            "total": 5,
        },
        "checks": [
            {"id": "review-file-configured", "level": "pass", "passed": True, "message": "A skill proposal review file is configured.", "evidence": {}},
            {"id": "review-file-exists", "level": "pass", "passed": True, "message": "The review file exists.", "evidence": {}},
            {"id": "review-file-valid", "level": "pass", "passed": True, "message": "The review file is valid and has a decisions array.", "evidence": {}},
            {"id": "current-proposals-cleared", "level": "pass", "passed": True, "message": "All current proposals are applied or rejected.", "evidence": {}},
            {"id": "no-stale-review-decisions", "level": "pass", "passed": True, "message": "No stale review decisions were found.", "evidence": {}},
        ],
        "recommendations": [{"level": "info", "text": "Review decisions clear the current skill proposal gate."}],
        "privacy": {
            "mutatesProfile": False,
            "mutatesSkillFiles": False,
            "callsExternalAiApis": False,
            "storesRawBriefText": False,
            "exposesEntryTextPreview": False,
        },
    }
    assert_skill_proposal_review_check_json(
        json.dumps(learning_skill_proposal_review_check_payload),
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        review_path=learning_skill_proposal_review_path,
        context=context,
        cmd=[*learn_skill_proposals_cmd[:-1], "--review-file", str(learning_skill_proposal_review_path), "--review-check", "--json"],
    )
    return learn_skill_proposals_cmd, learning_skill_proposal_payload, learning_skill_proposal_review_check_payload, learning_skill_proposal_review_path


def _self_test_learn_proposal_review_files(context, learn_skill_proposals_cmd, learning_profile_path, learning_skill_proposal_review_path, learning_usage_path, tmp):
    """Package smoke self-test: learn skill-proposal review file contracts."""
    learning_skill_proposal_review_check_markdown = "\n".join([
        "# Skill Proposal Review Check",
        "",
        "- Generated: 2026-06-11T00:05:00.000Z",
        "- Status: pass",
        "- Proposal status: pass",
        "- Signal status: pass",
        f"- File: {learning_profile_path}",
        f"- Usage sidecar: {learning_usage_path}",
        f"- Signal source: {Path(tmp)}",
        f"- Review file: {learning_skill_proposal_review_path}",
        "- Proposals: 1",
        "- Pending review: 0",
        "- Reviewed: 1",
        "",
        "## Checks",
        "",
        "- pass: review-file-configured - A skill proposal review file is configured.",
        "- pass: review-file-exists - The review file exists.",
        "- pass: review-file-valid - The review file is valid and has a decisions array.",
        "- pass: current-proposals-cleared - All current proposals are applied or rejected.",
        "- pass: no-stale-review-decisions - No stale review decisions were found.",
        "",
        "## Review Summary",
        "",
        "- Exists: yes",
        "- Status: pass",
        "- Decisions: 1",
        "- Matched: 1",
        "- Stale: 0",
        "- Applied: 1",
        "- Rejected: 0",
        "- Accepted: 0",
        "- Deferred: 0",
        "",
        "## Recommendations",
        "",
        "- info: Review decisions clear the current skill proposal gate.",
        "",
        "## Privacy And Boundaries",
        "",
        "- Mutates learning profile: no",
        "- Mutates skill files: no",
        "- Calls external AI APIs: no",
        "- Stores raw brief text: no",
    ])
    assert_skill_proposal_review_check_markdown(
        learning_skill_proposal_review_check_markdown,
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        review_path=learning_skill_proposal_review_path,
        context=context,
        cmd=[*learn_skill_proposals_cmd[:-1], "--review-file", str(learning_skill_proposal_review_path), "--review-check", "--report"],
    )
    learning_skill_proposal_apply_plan_review_path = learning_profile_path.with_name("skill-proposals.accepted.review.json")
    learning_skill_proposal_apply_plan_decision_command_safety = {
        "level": "local-output",
        "writesLocalFiles": True,
        "writesOutputArtifact": True,
        "mutatesLocalState": True,
        "mutatesProfile": False,
        "mutatesReviewFile": False,
        "mutatesSkillFiles": False,
        "callsExternalAiApis": False,
        "requiresCleanWorkspace": False,
        "reason": "This follow-up command writes a local preview artifact with --out but does not mutate learning, review, or skill files.",
    }
    return learning_skill_proposal_apply_plan_decision_command_safety, learning_skill_proposal_apply_plan_review_path, learning_skill_proposal_review_check_markdown


def _self_test_learn_apply_plan(context, learn_skill_proposals_cmd, learning_profile_path, learning_skill_proposal_apply_plan_decision_command_safety, learning_skill_proposal_apply_plan_review_path, learning_skill_proposal_payload, learning_usage_path, tmp):
    """Package smoke self-test: learn apply-plan generation and patch contracts."""
    learning_skill_proposal_apply_plan_payload = {
        "version": 1,
        "kind": "skill-proposal-apply-plan",
        "generatedAt": "2026-06-11T00:10:00.000Z",
        "file": str(learning_profile_path),
        "usageFile": str(learning_usage_path),
        "signalSource": str(Path(tmp)),
        "reviewFile": str(learning_skill_proposal_apply_plan_review_path),
        "status": "warn",
        "proposalStatus": "warn",
        "signalStatus": "pass",
        "candidateCount": 1,
        "proposalCount": 1,
        "acceptedCount": 1,
        "count": 1,
        "pendingReviewCount": 1,
        "reviewedCount": 1,
        "review": {
            **learning_skill_proposal_payload["review"],
            "file": str(learning_skill_proposal_apply_plan_review_path),
            "exists": True,
            "status": "pass",
            "decisionCount": 1,
            "matchedCount": 1,
            "pendingCount": 1,
            "acceptedCount": 1,
        },
        "tasks": [
            {
                "id": "apply-1-skill-proposal-component-spec-writer-abcdef1234",
                "proposalId": "skill-proposal-component-spec-writer-abcdef1234",
                "title": "Update skills/component-spec-writer/SKILL.md for repeated accessibility check captures",
                "candidateSkill": "component-spec-writer",
                "candidateSkillPath": "skills/component-spec-writer/SKILL.md",
                "category": "accessibility",
                "riskLevel": "low",
                "routeIds": [EXPECTED_ROUTE_ID],
                "sourceIssueCount": 2,
                "proposedInstructionDelta": "Add a pre-handoff accessibility checkpoint.",
                "verificationCommand": f"node cli/bin/design-ai.mjs check --examples --route {EXPECTED_ROUTE_ID} --limit 1 --strict --json",
                "manualSteps": [
                    "Open skills/component-spec-writer/SKILL.md and inspect the relevant checklist or playbook section.",
                    "Merge the proposed instruction delta manually instead of pasting duplicate generated text.",
                    "Run the verification command and inspect any route-specific failures before marking the work complete.",
                    "After the skill edit and verification pass, update the review decision from `accepted` to `applied`.",
                ],
                "safetyChecklist": [
                    "Do not edit learning.json as part of this apply plan.",
                    "Do not call external AI APIs, embeddings, or fine-tuning jobs.",
                ],
                "evidenceSources": learning_skill_proposal_payload["proposals"][0]["evidenceSources"],
                "reviewDecision": {
                    "proposalId": "skill-proposal-component-spec-writer-abcdef1234",
                    "status": "accepted",
                    "reviewedAt": "2026-06-11T00:10:00.000Z",
                    "reviewer": "package-smoke",
                    "note": "Instruction delta accepted for manual apply.",
                },
            },
        ],
        "commands": {
            "reviewCheckJson": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --json",
            "reviewCheckReport": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --report --out skill-proposal-review-check.md",
            "proposalPatchPreview": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --patch --out skill-proposals.patch",
            "strictGate": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --strict --json",
        },
        "commandArgs": {
            "reviewCheckJson": [
                "design-ai", "learn", "--propose-skills",
                "--file", str(learning_profile_path),
                "--usage-file", str(learning_usage_path),
                "--from-file", str(Path(tmp)),
                "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                "--review-check", "--json",
            ],
            "reviewCheckReport": [
                "design-ai", "learn", "--propose-skills",
                "--file", str(learning_profile_path),
                "--usage-file", str(learning_usage_path),
                "--from-file", str(Path(tmp)),
                "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                "--review-check", "--report", "--out", "skill-proposal-review-check.md",
            ],
            "proposalPatchPreview": [
                "design-ai", "learn", "--propose-skills",
                "--file", str(learning_profile_path),
                "--usage-file", str(learning_usage_path),
                "--from-file", str(Path(tmp)),
                "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                "--patch", "--out", "skill-proposals.patch",
            ],
            "strictGate": [
                "design-ai", "learn", "--propose-skills",
                "--file", str(learning_profile_path),
                "--usage-file", str(learning_usage_path),
                "--from-file", str(Path(tmp)),
                "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                "--strict", "--json",
            ],
        },
        "commandContract": {
            "version": 1,
            "valid": True,
            "status": "pass",
            "commandCount": 4,
            "checkCount": 18,
            "passCount": 18,
            "warningCount": 0,
            "requiredKeys": [
                "reviewCheckJson",
                "reviewCheckReport",
                "proposalPatchPreview",
                "strictGate",
            ],
            "missingCommandKeys": [],
            "unexpectedCommandKeys": [],
            "baseCommand": ["design-ai", "learn", "--propose-skills"],
            "reviewFileRequired": True,
            "reviewFile": str(learning_skill_proposal_apply_plan_review_path),
            "forbiddenFlags": ["--yes"],
            "failureCount": 0,
            "failedCheckIds": [],
            "failedChecks": [],
            "nextCommandKey": "reviewCheckJson",
            "nextCommand": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --json",
            "nextCommandArgs": [
                "design-ai", "learn", "--propose-skills",
                "--file", str(learning_profile_path),
                "--usage-file", str(learning_usage_path),
                "--from-file", str(Path(tmp)),
                "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                "--review-check", "--json",
            ],
            "nextCommandRunPolicy": "preview-only",
            "nextCommandSafety": {
                "level": "read-only",
                "writesLocalFiles": False,
                "mutatesLocalState": False,
                "mutatesProfile": False,
                "mutatesReviewFile": False,
                "mutatesSkillFiles": False,
                "callsExternalAiApis": False,
                "requiresCleanWorkspace": False,
                "reason": "The next apply-plan follow-up command only checks proposal review readiness and does not mutate local state.",
            },
            "commandSequenceCount": 4,
            "commandSequenceSummary": {
                "executable": True,
                "blocked": False,
                "stepCount": 4,
                "readOnlyStepCount": 2,
                "localOutputStepCount": 2,
                "writesLocalFiles": True,
                "writesOutputArtifacts": True,
                "mutatesProfile": False,
                "mutatesReviewFile": False,
                "mutatesSkillFiles": False,
                "callsExternalAiApis": False,
                "requiresCleanWorkspace": False,
                "runPolicy": "mixed-preview-local-output",
                "reason": "The sequence combines read-only readiness checks with local output artifact previews; it does not mutate learning, review, or skill files.",
            },
            "commandSequenceKeys": [
                "reviewCheckJson",
                "reviewCheckReport",
                "proposalPatchPreview",
                "strictGate",
            ],
            "commandSequenceByKey": {
                "reviewCheckJson": {
                    "key": "reviewCheckJson",
                    "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --json",
                    "runPolicy": "preview-only",
                    "safety": {"level": "read-only"},
                },
                "reviewCheckReport": {
                    "key": "reviewCheckReport",
                    "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --report --out skill-proposal-review-check.md",
                    "runPolicy": "output-artifact",
                    "safety": {"level": "local-output"},
                },
                "proposalPatchPreview": {
                    "key": "proposalPatchPreview",
                    "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --patch --out skill-proposals.patch",
                    "runPolicy": "output-artifact",
                    "safety": {"level": "local-output"},
                },
                "strictGate": {
                    "key": "strictGate",
                    "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --strict --json",
                    "runPolicy": "strict-readiness-gate",
                    "safety": {"level": "read-only"},
                },
            },
            "commandSequence": [
                {
                    "step": 1,
                    "key": "reviewCheckJson",
                    "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --json",
                    "commandArgs": [
                        "design-ai", "learn", "--propose-skills",
                        "--file", str(learning_profile_path),
                        "--usage-file", str(learning_usage_path),
                        "--from-file", str(Path(tmp)),
                        "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                        "--review-check", "--json",
                    ],
                    "runPolicy": "preview-only",
                    "safety": {
                        "level": "read-only",
                        "writesLocalFiles": False,
                        "writesOutputArtifact": False,
                        "mutatesLocalState": False,
                        "mutatesProfile": False,
                        "mutatesReviewFile": False,
                        "mutatesSkillFiles": False,
                        "callsExternalAiApis": False,
                        "requiresCleanWorkspace": False,
                        "reason": "This follow-up command validates readiness without writing local files or mutating local state.",
                    },
                },
                {
                    "step": 2,
                    "key": "reviewCheckReport",
                    "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --report --out skill-proposal-review-check.md",
                    "commandArgs": [
                        "design-ai", "learn", "--propose-skills",
                        "--file", str(learning_profile_path),
                        "--usage-file", str(learning_usage_path),
                        "--from-file", str(Path(tmp)),
                        "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                        "--review-check", "--report", "--out", "skill-proposal-review-check.md",
                    ],
                    "runPolicy": "output-artifact",
                    "safety": {
                        "level": "local-output",
                        "writesLocalFiles": True,
                        "writesOutputArtifact": True,
                        "mutatesLocalState": True,
                        "mutatesProfile": False,
                        "mutatesReviewFile": False,
                        "mutatesSkillFiles": False,
                        "callsExternalAiApis": False,
                        "requiresCleanWorkspace": False,
                        "reason": "This follow-up command writes a local preview artifact with --out but does not mutate learning, review, or skill files.",
                    },
                },
                {
                    "step": 3,
                    "key": "proposalPatchPreview",
                    "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --patch --out skill-proposals.patch",
                    "commandArgs": [
                        "design-ai", "learn", "--propose-skills",
                        "--file", str(learning_profile_path),
                        "--usage-file", str(learning_usage_path),
                        "--from-file", str(Path(tmp)),
                        "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                        "--patch", "--out", "skill-proposals.patch",
                    ],
                    "runPolicy": "output-artifact",
                    "safety": {
                        "level": "local-output",
                        "writesLocalFiles": True,
                        "writesOutputArtifact": True,
                        "mutatesLocalState": True,
                        "mutatesProfile": False,
                        "mutatesReviewFile": False,
                        "mutatesSkillFiles": False,
                        "callsExternalAiApis": False,
                        "requiresCleanWorkspace": False,
                        "reason": "This follow-up command writes a local preview artifact with --out but does not mutate learning, review, or skill files.",
                    },
                },
                {
                    "step": 4,
                    "key": "strictGate",
                    "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --strict --json",
                    "commandArgs": [
                        "design-ai", "learn", "--propose-skills",
                        "--file", str(learning_profile_path),
                        "--usage-file", str(learning_usage_path),
                        "--from-file", str(Path(tmp)),
                        "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                        "--strict", "--json",
                    ],
                    "runPolicy": "strict-readiness-gate",
                    "safety": {
                        "level": "read-only",
                        "writesLocalFiles": False,
                        "writesOutputArtifact": False,
                        "mutatesLocalState": False,
                        "mutatesProfile": False,
                        "mutatesReviewFile": False,
                        "mutatesSkillFiles": False,
                        "callsExternalAiApis": False,
                        "requiresCleanWorkspace": False,
                        "reason": "This follow-up command validates readiness without writing local files or mutating local state.",
                    },
                },
            ],
            "operatorRunbook": {
                "version": 1,
                "executable": True,
                "blocked": False,
                "stageCount": 4,
                "requiredStageCount": 3,
                "commandStageCount": 3,
                "nextStageKey": "previewArtifacts",
                "nextStageCommandKeys": ["reviewCheckReport", "proposalPatchPreview"],
                "nextRequiredStageKey": "manualSkillEdit",
                "nextRequiredStageCommandKeys": [],
                "nextRequiredCommandStageKey": "reviewReadiness",
                "nextRequiredCommandStageCommandKeys": ["reviewCheckJson"],
                "stageSelection": {
                    "strategy": "optional-preview-before-required-manual-edit",
                    "decision": {
                        "action": "offer-optional-preview",
                        "stageKey": "previewArtifacts",
                        "stageKind": "local-output-preview",
                        "required": False,
                        "hasCommands": True,
                        "commandCount": 2,
                        "commandKeys": ["reviewCheckReport", "proposalPatchPreview"],
                        "commands": [
                            {
                                "step": 2,
                                "key": "reviewCheckReport",
                                "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --report --out skill-proposal-review-check.md",
                                "commandArgs": [
                                    "design-ai", "learn", "--propose-skills",
                                    "--file", str(learning_profile_path),
                                    "--usage-file", str(learning_usage_path),
                                    "--from-file", str(Path(tmp)),
                                    "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                                    "--review-check", "--report", "--out", "skill-proposal-review-check.md",
                                ],
                                "runPolicy": "output-artifact",
                                "safetyLevel": "local-output",
                                "safety": learning_skill_proposal_apply_plan_decision_command_safety,
                                "writesLocalFiles": True,
                                "writesOutputArtifact": True,
                                "mutatesLocalState": True,
                                "mutatesProfile": False,
                                "mutatesReviewFile": False,
                                "mutatesSkillFiles": False,
                                "callsExternalAiApis": False,
                                "requiresCleanWorkspace": False,
                            },
                            {
                                "step": 3,
                                "key": "proposalPatchPreview",
                                "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --patch --out skill-proposals.patch",
                                "commandArgs": [
                                    "design-ai", "learn", "--propose-skills",
                                    "--file", str(learning_profile_path),
                                    "--usage-file", str(learning_usage_path),
                                    "--from-file", str(Path(tmp)),
                                    "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                                    "--patch", "--out", "skill-proposals.patch",
                                ],
                                "runPolicy": "output-artifact",
                                "safetyLevel": "local-output",
                                "safety": learning_skill_proposal_apply_plan_decision_command_safety,
                                "writesLocalFiles": True,
                                "writesOutputArtifact": True,
                                "mutatesLocalState": True,
                                "mutatesProfile": False,
                                "mutatesReviewFile": False,
                                "mutatesSkillFiles": False,
                                "callsExternalAiApis": False,
                                "requiresCleanWorkspace": False,
                            },
                        ],
                        "commandByKey": {
                            "reviewCheckReport": {
                                "step": 2,
                                "key": "reviewCheckReport",
                                "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --report --out skill-proposal-review-check.md",
                                "commandArgs": [
                                    "design-ai", "learn", "--propose-skills",
                                    "--file", str(learning_profile_path),
                                    "--usage-file", str(learning_usage_path),
                                    "--from-file", str(Path(tmp)),
                                    "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                                    "--review-check", "--report", "--out", "skill-proposal-review-check.md",
                                ],
                                "runPolicy": "output-artifact",
                                "safetyLevel": "local-output",
                                "safety": learning_skill_proposal_apply_plan_decision_command_safety,
                                "writesLocalFiles": True,
                                "writesOutputArtifact": True,
                                "mutatesLocalState": True,
                                "mutatesProfile": False,
                                "mutatesReviewFile": False,
                                "mutatesSkillFiles": False,
                                "callsExternalAiApis": False,
                                "requiresCleanWorkspace": False,
                            },
                            "proposalPatchPreview": {
                                "step": 3,
                                "key": "proposalPatchPreview",
                                "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --patch --out skill-proposals.patch",
                                "commandArgs": [
                                    "design-ai", "learn", "--propose-skills",
                                    "--file", str(learning_profile_path),
                                    "--usage-file", str(learning_usage_path),
                                    "--from-file", str(Path(tmp)),
                                    "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                                    "--patch", "--out", "skill-proposals.patch",
                                ],
                                "runPolicy": "output-artifact",
                                "safetyLevel": "local-output",
                                "safety": learning_skill_proposal_apply_plan_decision_command_safety,
                                "writesLocalFiles": True,
                                "writesOutputArtifact": True,
                                "mutatesLocalState": True,
                                "mutatesProfile": False,
                                "mutatesReviewFile": False,
                                "mutatesSkillFiles": False,
                                "callsExternalAiApis": False,
                                "requiresCleanWorkspace": False,
                            },
                        },
                        "commandStepByKey": {
                            "reviewCheckReport": 2,
                            "proposalPatchPreview": 3,
                        },
                        "commandRunPolicyByKey": {
                            "reviewCheckReport": "output-artifact",
                            "proposalPatchPreview": "output-artifact",
                        },
                        "commandSafetyLevelByKey": {
                            "reviewCheckReport": "local-output",
                            "proposalPatchPreview": "local-output",
                        },
                        "commandArgsByKey": {
                            "reviewCheckReport": [
                                "design-ai", "learn", "--propose-skills",
                                "--file", str(learning_profile_path),
                                "--usage-file", str(learning_usage_path),
                                "--from-file", str(Path(tmp)),
                                "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                                "--review-check", "--report", "--out", "skill-proposal-review-check.md",
                            ],
                            "proposalPatchPreview": [
                                "design-ai", "learn", "--propose-skills",
                                "--file", str(learning_profile_path),
                                "--usage-file", str(learning_usage_path),
                                "--from-file", str(Path(tmp)),
                                "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                                "--patch", "--out", "skill-proposals.patch",
                            ],
                        },
                        "commandStringByKey": {
                            "reviewCheckReport": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --report --out skill-proposal-review-check.md",
                            "proposalPatchPreview": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --patch --out skill-proposals.patch",
                        },
                        "commandDisplayLabelByKey": {
                            "reviewCheckReport": "Review check Markdown report",
                            "proposalPatchPreview": "Skill proposal patch preview",
                        },
                        "commandDescriptionByKey": {
                            "reviewCheckReport": "Generate a Markdown review-check artifact for accepted proposal readiness.",
                            "proposalPatchPreview": "Generate a unified diff preview for accepted skill proposal edits.",
                        },
                        "commandOutputArtifactByKey": {
                            "reviewCheckReport": "skill-proposal-review-check.md",
                            "proposalPatchPreview": "skill-proposals.patch",
                        },
                        "commandOutputArtifactTypeByKey": {
                            "reviewCheckReport": "markdown-report",
                            "proposalPatchPreview": "unified-diff",
                        },
                        "commandOutputArtifactActionByKey": {
                            "reviewCheckReport": "render-markdown-report",
                            "proposalPatchPreview": "render-unified-diff-preview",
                        },
                        "commandOutputArtifactMediaTypeByKey": {
                            "reviewCheckReport": "text/markdown",
                            "proposalPatchPreview": "text/x-diff",
                        },
                        "commandOutputArtifactDispositionByKey": {
                            "reviewCheckReport": "review-only",
                            "proposalPatchPreview": "manual-apply-preview",
                        },
                        "commandOutputArtifactManualApplyCandidateByKey": {
                            "reviewCheckReport": False,
                            "proposalPatchPreview": True,
                        },
                        "commandOutputArtifactRequiresManualReviewByKey": {
                            "reviewCheckReport": False,
                            "proposalPatchPreview": True,
                        },
                        "commandOutputArtifactReviewInstructionByKey": {
                            "reviewCheckReport": "Review the Markdown readiness report before changing proposal review status.",
                            "proposalPatchPreview": "Review the unified diff manually before applying any skill-file edits.",
                        },
                        "commandOutputArtifactRequiresCleanWorkspaceBeforeApplyByKey": {
                            "reviewCheckReport": False,
                            "proposalPatchPreview": True,
                        },
                        "commandOutputArtifactApplyPreconditionIdsByKey": {
                            "reviewCheckReport": [],
                            "proposalPatchPreview": ["manual-review", "clean-workspace"],
                        },
                        "commandOutputArtifactApplyPreconditionLabelsByKey": {
                            "reviewCheckReport": [],
                            "proposalPatchPreview": ["Manual review completed", "Clean workspace confirmed"],
                        },
                        "commandOutputArtifactApplyPreconditionsByKey": {
                            "reviewCheckReport": [],
                            "proposalPatchPreview": [
                                {"id": "manual-review", "label": "Manual review completed", "required": True},
                                {"id": "clean-workspace", "label": "Clean workspace confirmed", "required": True},
                            ],
                        },
                        "commandOutputArtifactApplyPreconditionCountByKey": {
                            "reviewCheckReport": 0,
                            "proposalPatchPreview": 2,
                        },
                        "commandOutputArtifactRequiredApplyPreconditionCountByKey": {
                            "reviewCheckReport": 0,
                            "proposalPatchPreview": 2,
                        },
                        "commandOutputArtifactSatisfiedApplyPreconditionCountByKey": {
                            "reviewCheckReport": 0,
                            "proposalPatchPreview": 0,
                        },
                        "commandOutputArtifactPendingApplyPreconditionCountByKey": {
                            "reviewCheckReport": 0,
                            "proposalPatchPreview": 2,
                        },
                        "commandOutputArtifactRequiredPendingApplyPreconditionCountByKey": {
                            "reviewCheckReport": 0,
                            "proposalPatchPreview": 2,
                        },
                        "commandOutputArtifactManualApplyReadyByKey": {
                            "reviewCheckReport": False,
                            "proposalPatchPreview": False,
                        },
                        "commandOutputArtifactManualApplyStatusByKey": {
                            "reviewCheckReport": "not-applicable",
                            "proposalPatchPreview": "blocked",
                        },
                        "commandOutputArtifactManualApplyStatusLabelByKey": {
                            "reviewCheckReport": "Review only",
                            "proposalPatchPreview": "Blocked",
                        },
                        "commandOutputArtifactManualApplyStatusToneByKey": {
                            "reviewCheckReport": "neutral",
                            "proposalPatchPreview": "warning",
                        },
                        "commandOutputArtifactManualApplyBlockedReasonByKey": {
                            "reviewCheckReport": "This output artifact is review-only and cannot be applied.",
                            "proposalPatchPreview": "Complete required apply preconditions before applying this patch preview.",
                        },
                        "commandOutputArtifactManualApplyBlockedReasonCodeByKey": {
                            "reviewCheckReport": "not-manual-apply-candidate",
                            "proposalPatchPreview": "required-preconditions-pending",
                        },
                        "nextCommandEntry": {
                            "step": 2,
                            "key": "reviewCheckReport",
                            "command": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --report --out skill-proposal-review-check.md",
                            "commandArgs": [
                                "design-ai", "learn", "--propose-skills",
                                "--file", str(learning_profile_path),
                                "--usage-file", str(learning_usage_path),
                                "--from-file", str(Path(tmp)),
                                "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                                "--review-check", "--report", "--out", "skill-proposal-review-check.md",
                            ],
                            "runPolicy": "output-artifact",
                            "safetyLevel": "local-output",
                            "safety": learning_skill_proposal_apply_plan_decision_command_safety,
                            "writesLocalFiles": True,
                            "writesOutputArtifact": True,
                            "mutatesLocalState": True,
                            "mutatesProfile": False,
                            "mutatesReviewFile": False,
                            "mutatesSkillFiles": False,
                            "callsExternalAiApis": False,
                            "requiresCleanWorkspace": False,
                        },
                        "nextCommandKey": "reviewCheckReport",
                        "nextCommandDisplayLabel": "Review check Markdown report",
                        "nextCommandDescription": "Generate a Markdown review-check artifact for accepted proposal readiness.",
                        "nextCommandOutputArtifact": "skill-proposal-review-check.md",
                        "nextCommandOutputArtifactType": "markdown-report",
                        "nextCommandOutputArtifactAction": "render-markdown-report",
                        "nextCommandOutputArtifactMediaType": "text/markdown",
                        "nextCommandOutputArtifactDisposition": "review-only",
                        "nextCommandOutputArtifactManualApplyCandidate": False,
                        "nextCommandOutputArtifactRequiresManualReview": False,
                        "nextCommandOutputArtifactReviewInstruction": "Review the Markdown readiness report before changing proposal review status.",
                        "nextCommandOutputArtifactRequiresCleanWorkspaceBeforeApply": False,
                        "nextCommandOutputArtifactApplyPreconditionIds": [],
                        "nextCommandOutputArtifactApplyPreconditionLabels": [],
                        "nextCommandOutputArtifactApplyPreconditions": [],
                        "nextCommandOutputArtifactApplyPreconditionCount": 0,
                        "nextCommandOutputArtifactRequiredApplyPreconditionCount": 0,
                        "nextCommandOutputArtifactSatisfiedApplyPreconditionCount": 0,
                        "nextCommandOutputArtifactPendingApplyPreconditionCount": 0,
                        "nextCommandOutputArtifactRequiredPendingApplyPreconditionCount": 0,
                        "nextCommandOutputArtifactManualApplyReady": False,
                        "nextCommandOutputArtifactManualApplyStatus": "not-applicable",
                        "nextCommandOutputArtifactManualApplyStatusLabel": "Review only",
                        "nextCommandOutputArtifactManualApplyStatusTone": "neutral",
                        "nextCommandOutputArtifactManualApplyBlockedReason": "This output artifact is review-only and cannot be applied.",
                        "nextCommandOutputArtifactManualApplyBlockedReasonCode": "not-manual-apply-candidate",
                        "nextCommandStep": 2,
                        "nextCommand": f"design-ai learn --propose-skills --file {learning_profile_path} --usage-file {learning_usage_path} --from-file {Path(tmp)} --review-file {learning_skill_proposal_apply_plan_review_path} --review-check --report --out skill-proposal-review-check.md",
                        "nextCommandArgs": [
                            "design-ai", "learn", "--propose-skills",
                            "--file", str(learning_profile_path),
                            "--usage-file", str(learning_usage_path),
                            "--from-file", str(Path(tmp)),
                            "--review-file", str(learning_skill_proposal_apply_plan_review_path),
                            "--review-check", "--report", "--out", "skill-proposal-review-check.md",
                        ],
                        "nextCommandRunPolicy": "output-artifact",
                        "nextCommandSafetyLevel": "local-output",
                        "nextCommandSafety": learning_skill_proposal_apply_plan_decision_command_safety,
                        "runPolicy": "optional-local-output-preview",
                        "safety": {
                            "level": "local-output",
                            "writesLocalFiles": True,
                            "writesOutputArtifacts": True,
                            "mutatesLocalState": True,
                            "mutatesProfile": False,
                            "mutatesReviewFile": False,
                            "mutatesSkillFiles": False,
                            "callsExternalAiApis": False,
                            "requiresCleanWorkspace": False,
                            "reason": "The selected decision only writes optional local preview artifacts and does not mutate learning, review, or skill files.",
                        },
                        "nextRequiredStageKey": "manualSkillEdit",
                        "nextRequiredCommandStageKey": "reviewReadiness",
                        "requiresOperatorActionBeforeRequiredCommands": True,
                        "reason": "Offer optional local preview artifacts first; the required path still starts with manual skill edits before read-only command gates.",
                    },
                    "stageOrder": ["previewArtifacts", "manualSkillEdit", "reviewReadiness", "strictGate"],
                    "nextStageKey": "previewArtifacts",
                    "nextStageCommandKeys": ["reviewCheckReport", "proposalPatchPreview"],
                    "nextStage": {
                        "key": "previewArtifacts",
                        "step": 1,
                        "label": "Generate optional review artifacts",
                        "kind": "local-output-preview",
                        "required": False,
                        "hasCommands": True,
                        "commandCount": 2,
                        "commandKeys": ["reviewCheckReport", "proposalPatchPreview"],
                        "writesLocalFiles": True,
                        "writesOutputArtifacts": True,
                        "mutatesLocalState": True,
                        "mutatesProfile": False,
                        "mutatesReviewFile": False,
                        "mutatesSkillFiles": False,
                        "callsExternalAiApis": False,
                        "requiresCleanWorkspace": False,
                        "reason": "Optional Markdown review and patch preview artifacts can be generated before manual skill edits.",
                    },
                    "nextRequiredStageKey": "manualSkillEdit",
                    "nextRequiredStageCommandKeys": [],
                    "nextRequiredStage": {
                        "key": "manualSkillEdit",
                        "step": 2,
                        "label": "Apply accepted skill deltas manually",
                        "kind": "manual-review",
                        "required": True,
                        "hasCommands": False,
                        "commandCount": 0,
                        "commandKeys": [],
                        "writesLocalFiles": False,
                        "writesOutputArtifacts": False,
                        "mutatesLocalState": False,
                        "mutatesProfile": False,
                        "mutatesReviewFile": False,
                        "mutatesSkillFiles": False,
                        "callsExternalAiApis": False,
                        "requiresCleanWorkspace": False,
                        "reason": "No apply-plan command mutates skill files; the operator must manually edit accepted skill deltas after review.",
                    },
                    "nextRequiredCommandStageKey": "reviewReadiness",
                    "nextRequiredCommandStageCommandKeys": ["reviewCheckJson"],
                    "nextRequiredCommandStage": {
                        "key": "reviewReadiness",
                        "step": 3,
                        "label": "Run review readiness check",
                        "kind": "read-only-check",
                        "required": True,
                        "hasCommands": True,
                        "commandCount": 1,
                        "commandKeys": ["reviewCheckJson"],
                        "writesLocalFiles": False,
                        "writesOutputArtifacts": False,
                        "mutatesLocalState": False,
                        "mutatesProfile": False,
                        "mutatesReviewFile": False,
                        "mutatesSkillFiles": False,
                        "callsExternalAiApis": False,
                        "requiresCleanWorkspace": False,
                        "reason": "Run the read-only review check after manual skill edits to verify proposal review state.",
                    },
                    "reason": "Offer optional local preview artifacts first, then require the manual skill edit before read-only review and strict gates.",
                },
                "stageKeys": ["previewArtifacts", "manualSkillEdit", "reviewReadiness", "strictGate"],
                "stageByKey": {
                    "previewArtifacts": {
                        "step": 1,
                        "key": "previewArtifacts",
                        "kind": "local-output-preview",
                        "required": False,
                        "commandKeys": ["reviewCheckReport", "proposalPatchPreview"],
                        "commands": [{"key": "reviewCheckReport"}, {"key": "proposalPatchPreview"}],
                    },
                    "manualSkillEdit": {
                        "step": 2,
                        "key": "manualSkillEdit",
                        "kind": "manual-review",
                        "required": True,
                        "commandKeys": [],
                        "commands": [],
                    },
                    "reviewReadiness": {
                        "step": 3,
                        "key": "reviewReadiness",
                        "kind": "read-only-check",
                        "required": True,
                        "commandKeys": ["reviewCheckJson"],
                        "commands": [{"key": "reviewCheckJson"}],
                    },
                    "strictGate": {
                        "step": 4,
                        "key": "strictGate",
                        "kind": "read-only-gate",
                        "required": True,
                        "commandKeys": ["strictGate"],
                        "commands": [{"key": "strictGate"}],
                    },
                },
                "stages": [
                    {
                        "step": 1,
                        "key": "previewArtifacts",
                        "kind": "local-output-preview",
                        "required": False,
                        "commandKeys": ["reviewCheckReport", "proposalPatchPreview"],
                        "commands": [{"key": "reviewCheckReport"}, {"key": "proposalPatchPreview"}],
                    },
                    {
                        "step": 2,
                        "key": "manualSkillEdit",
                        "kind": "manual-review",
                        "required": True,
                        "commandKeys": [],
                        "commands": [],
                    },
                    {
                        "step": 3,
                        "key": "reviewReadiness",
                        "kind": "read-only-check",
                        "required": True,
                        "commandKeys": ["reviewCheckJson"],
                        "commands": [{"key": "reviewCheckJson"}],
                    },
                    {
                        "step": 4,
                        "key": "strictGate",
                        "kind": "read-only-gate",
                        "required": True,
                        "commandKeys": ["strictGate"],
                        "commands": [{"key": "strictGate"}],
                    },
                ],
                "reason": "Generate optional local review artifacts, apply accepted skill deltas manually, then run read-only review and strict readiness gates.",
            },
            "nextAction": "Run reviewCheckJson after manual skill edits, then use strictGate before marking proposals applied.",
            "checks": [
                {"id": "required-command-keys-present", "level": "pass", "passed": True},
                {"id": "no-unexpected-command-keys", "level": "pass", "passed": True},
                {"id": "reviewCheckJson-base-command", "level": "pass", "passed": True},
                {"id": "reviewCheckJson-review-file-context", "level": "pass", "passed": True},
                {"id": "reviewCheckJson-expected-suffix", "level": "pass", "passed": True},
                {"id": "reviewCheckJson-read-only-flags", "level": "pass", "passed": True},
                {"id": "reviewCheckReport-base-command", "level": "pass", "passed": True},
                {"id": "reviewCheckReport-review-file-context", "level": "pass", "passed": True},
                {"id": "reviewCheckReport-expected-suffix", "level": "pass", "passed": True},
                {"id": "reviewCheckReport-read-only-flags", "level": "pass", "passed": True},
                {"id": "proposalPatchPreview-base-command", "level": "pass", "passed": True},
                {"id": "proposalPatchPreview-review-file-context", "level": "pass", "passed": True},
                {"id": "proposalPatchPreview-expected-suffix", "level": "pass", "passed": True},
                {"id": "proposalPatchPreview-read-only-flags", "level": "pass", "passed": True},
                {"id": "strictGate-base-command", "level": "pass", "passed": True},
                {"id": "strictGate-review-file-context", "level": "pass", "passed": True},
                {"id": "strictGate-expected-suffix", "level": "pass", "passed": True},
                {"id": "strictGate-read-only-flags", "level": "pass", "passed": True},
            ],
            "summary": {
                "failures": 0,
                "warnings": 0,
                "passes": 18,
                "total": 18,
            },
        },
        "recommendations": [{"level": "warning", "text": "Apply accepted proposal deltas manually."}],
        "privacy": {
            "mutatesProfile": False,
            "mutatesReviewFile": False,
            "mutatesSkillFiles": False,
            "callsExternalAiApis": False,
            "storesRawBriefText": False,
            "exposesEntryTextPreview": True,
        },
    }
    assert_skill_proposal_apply_plan_json(
        json.dumps(learning_skill_proposal_apply_plan_payload),
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        review_path=learning_skill_proposal_apply_plan_review_path,
        signal_source=Path(tmp),
        context=context,
        cmd=[*learn_skill_proposals_cmd[:-1], "--review-file", str(learning_skill_proposal_apply_plan_review_path), "--apply-plan", "--json"],
    )
    return learning_skill_proposal_apply_plan_payload
