"""Package smoke self-test: learn usage capture, signal reports, and skill-proposal generation."""
from __future__ import annotations

import json

from pathlib import Path
from smoke_assertions import (
    EXPECTED_ROUTE_BRIEF,
    EXPECTED_ROUTE_ID,
    expect_self_test_failure,
)
from smoke_domains.package_learning_agent_backlog import assert_agent_backlog_report_json
from smoke_domains.package_learning_agent_backlog_reports import (
    assert_agent_backlog_no_command_json,
    assert_agent_backlog_no_command_report_markdown,
)
from smoke_domains.package_learning_relevance import assert_learning_usage_sidecar
from smoke_domains.package_learning_relevance_reports import (
    assert_learning_signal_report_human,
    assert_learning_signal_report_json,
    assert_learning_signal_report_markdown,
    assert_learning_usage_report_human,
    assert_learning_usage_report_json,
)
from smoke_domains.package_selftest_support import (
    EXPECTED_AGENT_BACKLOG_EMPTY_QUEUE_ALIGNMENT_REASON,
    EXPECTED_AGENT_BACKLOG_NO_COMMAND_HANDOFF_REASON,
    EXPECTED_AGENT_BACKLOG_REFRESH_ONLY_RUNBOOK_REASON,
    EXPECTED_CHECK_CAPTURE_OPTIONAL_GAP_AUTOMATION_POLICY,
    EXPECTED_CHECK_CAPTURE_OPTIONAL_GAP_NEXT_CONDITION,
    EXPECTED_CHECK_CAPTURE_OPTIONAL_GAP_REASON,
)


def _self_test_learn_usage_and_signals(context, learning_profile_path, learning_relevance_cmd, learning_relevance_payload, learning_usage_path, tmp) -> None:
    """Package smoke self-test: learn usage capture and signal report contracts."""
    learning_usage_report_payload = {
        "file": str(learning_profile_path),
        "usageFile": str(learning_usage_path),
        "exists": True,
        "profileExists": True,
        "profileFile": str(learning_profile_path),
        "version": 1,
        "updatedAt": "2026-06-01T00:00:01.000Z",
        "eventCount": 2,
        "profileEntryCount": 3,
        "usedEntryCount": 1,
        "unusedEntryCount": 2,
        "staleSelectedEntryCount": 0,
        "commandCounts": {
            "prompt": 1,
            "pack": 1,
        },
        "routeCounts": {
            EXPECTED_ROUTE_ID: 2,
        },
        "categoryCounts": {
            "all": 2,
        },
        "auditStatusCounts": {
            "pass": 2,
        },
        "selectedEntryCounts": {
            "learn-relevant": 2,
        },
        "topSelectedEntries": [
            {
                "id": "learn-relevant",
                "category": "accessibility",
                "source": "package-smoke",
                "textPreview": "Prioritize keyboard accessibility details for Button component API specs",
                "usageCount": 2,
                "latestUsedAt": "2026-06-01T00:00:01.000Z",
                "commands": {
                    "prompt": 1,
                    "pack": 1,
                },
                "routes": {
                    EXPECTED_ROUTE_ID: 2,
                },
            },
        ],
        "unusedEntryIds": ["learn-unrelated-newer", "learn-brand"],
        "staleSelectedEntryIds": [],
        "oldestEvent": {
            **learning_relevance_payload["learningUsage"]["event"],
            "id": "learn-use-prompt",
            "command": "prompt",
        },
        "latestEvent": {
            **learning_relevance_payload["learningUsage"]["event"],
            "id": "learn-use-pack",
            "command": "pack",
            "createdAt": "2026-06-01T00:00:01.000Z",
        },
        "recentEvents": [
            {
                **learning_relevance_payload["learningUsage"]["event"],
                "id": "learn-use-pack",
                "command": "pack",
                "createdAt": "2026-06-01T00:00:01.000Z",
            },
        ],
        "recommendations": [],
        "privacy": {
            "storesRawBriefText": False,
            "storesBriefHash": True,
            "storesSelectedEntryIds": True,
        },
    }
    learn_usage_cmd = ["design-ai", "learn", "--usage", "--file", str(learning_profile_path), "--usage-file", str(learning_usage_path), "--json"]
    assert_learning_usage_report_json(
        json.dumps(learning_usage_report_payload),
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        context=context,
        cmd=learn_usage_cmd,
    )
    assert_learning_usage_report_human(
        "\n".join([
            "design-ai learn",
            "Local learning usage report",
            f"Usage sidecar: {learning_usage_path}",
            "Events: 2",
            "Top selected entries:",
            "Recent events:",
            "Privacy: usage events store selected entry ids and a short brief hash",
        ]),
        context=context,
        cmd=learn_usage_cmd,
    )
    expect_self_test_failure(
        lambda: assert_learning_usage_report_json(
            json.dumps({
                **learning_usage_report_payload,
                "latestEvent": {
                    **learning_usage_report_payload["latestEvent"],
                    "brief": EXPECTED_ROUTE_BRIEF,
                    "briefHash": "",
                },
            }),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_usage_cmd,
        ),
        expected="learn usage report should keep event details privacy-preserving",
        scope="package smoke",
    )
    expect_self_test_failure(
        lambda: assert_learning_usage_sidecar(
            learning_usage_path.with_name("missing-usage.json"),
            expected_commands=["prompt", "pack"],
            context=context,
            cmd=learning_relevance_cmd,
        ),
        expected="learning usage sidecar file should be written",
        scope="package smoke",
    )

    learn_signals_cmd = [
        "design-ai",
        "learn",
        "--signals",
        "--file",
        str(learning_profile_path),
        "--usage-file",
        str(learning_usage_path),
        "--from-file",
        str(Path(tmp)),
        "--json",
    ]
    learning_signal_payload = {
        "version": 1,
        "generatedAt": "2026-06-02T00:00:00.000Z",
        "status": "pass",
        "file": str(learning_profile_path),
        "signalSource": str(Path(tmp)),
        "learning": {
            "exists": True,
            "version": 1,
            "updatedAt": "2026-06-01T00:00:00.000Z",
            "count": 3,
            "categoryCounts": {"workflow": 2, "brand": 1},
            "sourceCounts": {"feedback:keep": 2, "check:artifact": 1},
            "auditSummary": {"status": "pass", "failures": 0, "warnings": 0},
        },
        "usage": {
            "usageFile": str(learning_usage_path),
            "exists": True,
            "eventCount": 2,
            "usedEntryCount": 2,
            "unusedEntryCount": 1,
            "staleSelectedEntryCount": 0,
            "commandCounts": {"prompt": 1, "pack": 1},
            "routeCounts": {EXPECTED_ROUTE_ID: 2},
            "latestEvent": learning_usage_report_payload["latestEvent"],
            "privacy": learning_usage_report_payload["privacy"],
        },
        "evals": {
            "source": str(Path(tmp)),
            "count": 1,
            "reports": 1,
            "templates": 0,
            "failed": 0,
            "warned": 0,
            "passed": 1,
            "files": [
                {
                    "file": str(Path(tmp) / "route-eval-report.json"),
                    "exists": True,
                    "kind": "route-eval",
                    "shape": "report",
                    "status": "pass",
                    "caseCount": 1,
                    "passed": 1,
                    "warned": 0,
                    "failed": 0,
                    "generatedAt": "2026-06-02T00:00:00.000Z",
                    "error": "",
                },
            ],
        },
        "checkCapture": {
            "count": 1,
            "categoryCounts": {"workflow": 1},
            "sourceCounts": {"check:artifact": 1},
            "latestEntries": [
                {
                    "id": "learn-check",
                    "category": "workflow",
                    "source": "check:artifact",
                    "createdAt": "2026-06-01T00:00:00.000Z",
                    "textPreview": "Improve future outputs by addressing responsive QA.",
                },
            ],
        },
        "workspace": {
            "root": str(Path(tmp)),
            "version": "4.55.0",
            "git": {"isRepo": True, "branch": "main", "clean": True, "ahead": 0, "behind": 0},
            "repository": {"status": "pass", "canonical": True},
            "learning": {"status": "pass", "reason": ""},
            "learningUsage": {"status": "pass", "reason": ""},
            "learningEval": {"status": "pass", "reason": ""},
            "nextActionCounts": {},
            "nextActionCount": 0,
        },
        "readiness": {
            "version": 1,
            "status": "pass",
            "summary": "Required and optional local learning signal surfaces are complete.",
            "requiredPassCount": 4,
            "requiredCount": 4,
            "requiredReady": True,
            "blockingCount": 0,
            "optionalGapCount": 0,
            "blockingChecks": [],
            "optionalGaps": [],
            "optionalGapDetails": [],
            "requiredCheckIds": ["learning-profile", "eval-signals", "workspace-readiness", "agent-development"],
            "optionalCheckIds": ["usage-sidecar", "check-capture"],
            "checkStatusById": {
                "learning-profile": "pass",
                "usage-sidecar": "pass",
                "eval-signals": "pass",
                "check-capture": "pass",
                "workspace-readiness": "pass",
                "agent-development": "pass",
            },
            "checkRequiredById": {
                "learning-profile": True,
                "usage-sidecar": False,
                "eval-signals": True,
                "check-capture": False,
                "workspace-readiness": True,
                "agent-development": True,
            },
            "checkCountByStatus": {
                "pass": 6,
                "info": 0,
                "warn": 0,
                "fail": 0,
                "missing": 0,
                "template": 0,
                "unknown": 0,
            },
            "requiredCheckCountByStatus": {
                "pass": 4,
                "info": 0,
                "warn": 0,
                "fail": 0,
                "missing": 0,
                "template": 0,
                "unknown": 0,
            },
            "optionalCheckCountByStatus": {
                "pass": 2,
                "info": 0,
                "warn": 0,
                "fail": 0,
                "missing": 0,
                "template": 0,
                "unknown": 0,
            },
            "checks": [
                {"id": "learning-profile", "label": "Learning profile", "status": "pass", "required": True, "summary": "Profile is ready."},
                {"id": "usage-sidecar", "label": "Usage sidecar", "status": "pass", "required": False, "summary": "Usage is ready."},
                {"id": "eval-signals", "label": "Eval signals", "status": "pass", "required": True, "summary": "Eval is ready."},
                {"id": "check-capture", "label": "Check learning capture", "status": "pass", "required": False, "summary": "Check capture is ready."},
                {"id": "workspace-readiness", "label": "Workspace readiness", "status": "pass", "required": True, "summary": "Workspace is ready."},
                {"id": "agent-development", "label": "Agent development backlog", "status": "pass", "required": True, "summary": "Agent backlog is ready."},
            ],
        },
        "agentDevelopment": {
            "status": "pass",
            "actionCount": 1,
            "p0Count": 0,
            "p1Count": 0,
            "p2Count": 1,
            "p3Count": 0,
            "actions": [
                {
                    "rank": 1,
                    "id": "agent-skill-proposal-preview",
                    "priority": "p2",
                    "category": "skill-evolution",
                    "title": "Preview skill instruction deltas from repeated check-capture signals.",
                    "rationale": "Captured warn/fail check results can become deterministic skill improvements without mutating skill files automatically.",
                    "command": "design-ai learn --propose-skills --json",
                    "evidence": {"checkCaptureCount": 1},
                },
            ],
            "privacy": {
                "mutatesProfile": False,
                "mutatesSkillFiles": False,
                "callsExternalAiApis": False,
                "storesRawBriefText": False,
            },
        },
        "recommendations": [],
        "privacy": {
            "mutatesProfile": False,
            "storesRawBriefText": False,
            "exposesEntryTextPreview": True,
            "readsSignalFilesOnly": True,
        },
    }
    assert_learning_signal_report_json(
        json.dumps(learning_signal_payload),
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        context=context,
        cmd=learn_signals_cmd,
    )
    assert_learning_signal_report_human(
        "\n".join([
            "design-ai learn",
            "Learning signal registry",
            f"Signal source: {Path(tmp)}",
            "Learning audit: pass",
            "Eval signals:",
            "Workspace readiness:",
            "Agent development backlog:",
            "Privacy: signal registry is read-only",
        ]),
        context=context,
        cmd=learn_signals_cmd,
    )
    assert_learning_signal_report_markdown(
        "\n".join([
            "# Learning Signal Registry Report",
            "",
            f"- Learning file: {learning_profile_path}",
            f"- Usage file: {learning_usage_path}",
            "## Readiness Summary",
            "- Required ready: yes",
            "- Required checks: 4/4",
            "- Blocking checks: 0",
            "- Optional gaps: 0",
            "Readiness check index:",
            "- Required ids: learning-profile, eval-signals, workspace-readiness, agent-development",
            "- Optional ids: usage-sidecar, check-capture",
            "- Status index: learning-profile=pass, usage-sidecar=pass, eval-signals=pass, check-capture=pass, workspace-readiness=pass, agent-development=pass",
            "- Required index: learning-profile=yes, usage-sidecar=no, eval-signals=yes, check-capture=no, workspace-readiness=yes, agent-development=yes",
            "- Status counts: pass=6, info=0, warn=0, fail=0, missing=0, template=0, unknown=0",
            "- Required status counts: pass=4, info=0, warn=0, fail=0, missing=0, template=0, unknown=0",
            "- Optional status counts: pass=2, info=0, warn=0, fail=0, missing=0, template=0, unknown=0",
            "## Learning Profile",
            "## Usage Signals",
            "## Eval Signals",
            "## Check Capture",
            "## Workspace Readiness",
            "## Agent Development Backlog",
            "```bash",
            "design-ai learn --propose-skills --json",
            "```",
            "## Privacy And Boundaries",
            "- Mutates learning profile: no",
            "- Stores raw brief text: no",
            "This report is read-only evidence; it does not mutate learning profiles, usage sidecars, eval files, skill files, or target repositories.",
        ]),
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        context=context,
        cmd=[*learn_signals_cmd[:-1], "--report"],
    )
    expect_self_test_failure(
        lambda: assert_learning_signal_report_markdown(
            "\n".join([
                "# Learning Signal Registry Report",
                "",
                f"- Learning file: {learning_profile_path}",
                f"- Usage file: {learning_usage_path}",
                "## Readiness Summary",
                "- Required ready: yes",
                "- Required checks: 4/4",
                "- Blocking checks: 0",
                "- Optional gaps: 0",
                "Readiness checks:",
                "## Learning Profile",
                "## Usage Signals",
                "## Eval Signals",
                "## Check Capture",
                "## Workspace Readiness",
                "## Agent Development Backlog",
                "```bash",
                "design-ai learn --propose-skills --json",
                "```",
                "## Privacy And Boundaries",
                "- Mutates learning profile: no",
                "- Stores raw brief text: no",
                "This report is read-only evidence; it does not mutate learning profiles, usage sidecars, eval files, skill files, or target repositories.",
            ]),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=[*learn_signals_cmd[:-1], "--report"],
        ),
        expected="learn signals Markdown report missing 'Readiness check index:'",
        scope="package smoke",
    )
    expect_self_test_failure(
        lambda: assert_learning_signal_report_json(
            json.dumps({
                **learning_signal_payload,
                "evals": {
                    **learning_signal_payload["evals"],
                    "files": [],
                },
            }),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_signals_cmd,
        ),
        expected="learn signals JSON should include route eval signal files",
        scope="package smoke",
    )
    expect_self_test_failure(
        lambda: assert_learning_signal_report_json(
            json.dumps({
                **learning_signal_payload,
                "agentDevelopment": {
                    **learning_signal_payload["agentDevelopment"],
                    "status": "warn",
                },
            }),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_signals_cmd,
            require_agent_status_pass=True,
        ),
        expected="learn signals JSON should include passing agent development backlog actions",
        scope="package smoke",
    )
    expect_self_test_failure(
        lambda: assert_learning_signal_report_json(
            json.dumps({
                **learning_signal_payload,
                "agentDevelopment": {
                    **learning_signal_payload["agentDevelopment"],
                    "privacy": {
                        **learning_signal_payload["agentDevelopment"]["privacy"],
                        "callsExternalAiApis": True,
                    },
                },
            }),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_signals_cmd,
        ),
        expected="learn signals JSON should keep agent development backlog local and preview-only",
        scope="package smoke",
    )
    expect_self_test_failure(
        lambda: assert_learning_signal_report_human(
            "\n".join([
                "design-ai learn",
                "Learning signal registry",
                "Signal source:",
                "Learning audit:",
                "Eval signals:",
                "Privacy: signal registry is read-only",
            ]),
            context=context,
            cmd=learn_signals_cmd,
        ),
        expected="learn signals human output missing 'Workspace readiness:'",
        scope="package smoke",
    )


def _self_test_learn_skill_proposals(agent_backlog_refresh_args, agent_backlog_refresh_command, context, learn_agent_backlog_cmd, learning_profile_path, learning_usage_path, tmp):
    """Package smoke self-test: learn skill-proposal generation contracts."""
    learning_agent_backlog_payload = {
        "version": 1,
        "generatedAt": "2026-06-02T00:00:05.000Z",
        "status": "pass",
        "signalStatus": "pass",
        "file": str(learning_profile_path),
        "usageFile": str(learning_usage_path),
        "signalSource": str(Path(tmp)),
        "counts": {
            "actions": 1,
            "p0": 0,
            "p1": 0,
            "p2": 1,
            "p3": 0,
            "learningEntries": 3,
            "usageEvents": 2,
            "evalSignals": 1,
            "checkCaptures": 1,
            "workspaceNextActions": 0,
        },
        "actions": [
            {
                "rank": 1,
                "id": "agent-skill-proposal-preview",
                "priority": "p2",
                "category": "skill-evolution",
                "title": "Preview skill instruction deltas from repeated check-capture signals.",
                "rationale": "Captured warn/fail check results can become deterministic skill improvements without mutating skill files automatically.",
                "command": "design-ai learn --propose-skills --json",
                "evidence": {"checkCaptureCount": 1},
            },
        ],
        "actionPlan": {
            "version": 1,
            "stepCount": 1,
            "nextStep": {
                "rank": 1,
                "actionId": "agent-skill-proposal-preview",
                "priority": "p2",
                "category": "skill-evolution",
                "title": "Preview skill instruction deltas from repeated check-capture signals.",
                "command": "design-ai learn --propose-skills --json",
                "expectedOutcome": "Captured warn/fail check results can become deterministic skill improvements without mutating skill files automatically.",
                "verification": [
                    "Run the command and inspect the preview/report output before applying any follow-up changes.",
                    "Re-run `design-ai learn --agent-backlog --strict --json` after the step to confirm the backlog status improved.",
                ],
                "requiresReviewBeforeMutation": False,
                "commandSafety": {
                    "level": "read-only",
                    "writesLocalFiles": False,
                    "mutatesLocalState": False,
                    "requiresCleanWorkspace": False,
                    "detectedFlags": [],
                    "reason": "Command is preview/report oriented and has no detected mutation flags.",
                },
            },
            "steps": [
                {
                    "rank": 1,
                    "actionId": "agent-skill-proposal-preview",
                    "priority": "p2",
                    "category": "skill-evolution",
                    "title": "Preview skill instruction deltas from repeated check-capture signals.",
                    "command": "design-ai learn --propose-skills --json",
                    "expectedOutcome": "Captured warn/fail check results can become deterministic skill improvements without mutating skill files automatically.",
                    "verification": [
                        "Run the command and inspect the preview/report output before applying any follow-up changes.",
                        "Re-run `design-ai learn --agent-backlog --strict --json` after the step to confirm the backlog status improved.",
                    ],
                    "requiresReviewBeforeMutation": False,
                    "commandSafety": {
                        "level": "read-only",
                        "writesLocalFiles": False,
                        "mutatesLocalState": False,
                        "requiresCleanWorkspace": False,
                        "detectedFlags": [],
                        "outputTargets": [],
                        "profileTargets": [],
                        "usageTargets": [],
                        "mutationFlags": [],
                        "reason": "Command is preview/report oriented and has no detected mutation flags.",
                    },
                },
            ],
            "safetySummary": {
                "total": 1,
                "readOnly": 1,
                "writesLocalFile": 0,
                "mutatesLocalState": 0,
                "requiresCleanWorkspace": 0,
                "requiresReviewBeforeMutation": 0,
            },
            "executionQueue": {
                "orderedCount": 1,
                "commandManifestCount": 1,
                "previewCount": 1,
                "fileWriteReviewCount": 0,
                "mutationReviewCount": 0,
                "nextActionId": "agent-skill-proposal-preview",
                "nextCommand": "design-ai learn --propose-skills --json",
                "nextCommandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                "nextCommandRunPolicy": "preview-only",
                "nextCommandSelection": {
                    "strategy": "first-command-in-safety-ordered-queue",
                    "safetyOrder": ["read-only", "writes-local-file", "mutates-local-state"],
                    "actionId": "agent-skill-proposal-preview",
                    "rank": 1,
                    "safetyLevel": "read-only",
                    "runPolicy": "preview-only",
                    "planNextActionId": "agent-skill-proposal-preview",
                    "planNextActionRank": 1,
                    "matchesPlanNextAction": True,
                    "reason": "Selected the ranked next action because it is first in the safety-ordered queue.",
                },
                "nextCommandAlignment": {
                    "strategy": "compare-operator-runbook-next-command-to-execution-queue-next-command",
                    "operatorStage": "execute",
                    "operatorActionId": "agent-skill-proposal-preview",
                    "operatorCommand": "design-ai learn --propose-skills --json",
                    "operatorCommandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                    "queueActionId": "agent-skill-proposal-preview",
                    "queueCommand": "design-ai learn --propose-skills --json",
                    "queueCommandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                    "rankedNextActionId": "agent-skill-proposal-preview",
                    "matchesQueueNextCommand": True,
                    "matchesQueueNextAction": True,
                    "operatorRunsBeforeQueueCommand": False,
                    "queueMatchesRankedNextAction": True,
                    "reason": "Operator runbook starts with the same command as the safety-ordered execution queue.",
                },
                "operatorHandoff": {
                    "version": 1,
                    "decision": "run-shared-command",
                    "state": {
                        "version": 1,
                        "status": "ready",
                        "ready": True,
                        "hasCommand": True,
                        "complete": False,
                        "canRunWithoutReview": True,
                        "requiresGate": False,
                        "requiresRefresh": True,
                        "summary": "The handoff command can be presented or run, then refreshed with the focused backlog check.",
                    },
                    "source": "operator-runbook",
                    "phase": "execute",
                    "label": "Run agent-skill-proposal-preview",
                    "command": "design-ai learn --propose-skills --json",
                    "commandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                    "actionId": "agent-skill-proposal-preview",
                    "rank": 1,
                    "runPolicy": "preview-only",
                    "required": True,
                    "isGate": False,
                    "nextQueueActionId": "agent-skill-proposal-preview",
                    "nextQueueCommand": "design-ai learn --propose-skills --json",
                    "nextQueueCommandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                    "nextQueueCommandRequiresGate": False,
                    "operatorGateAppliesToNextQueueAction": False,
                    "nextQueueActionBlockedByGate": False,
                    "refreshCommand": agent_backlog_refresh_command,
                    "refreshCommandArgs": agent_backlog_refresh_args,
                    "refreshCommandLabel": "Refresh focused agent backlog after review",
                    "refreshCommandRequired": True,
                    "reviewLevel": "clear",
                    "requiresOperatorReview": False,
                    "reason": "Run the shared operator and queue command next.",
                },
                "commandEffectSummary": {
                    "totalCommands": 1,
                    "writesLocalFileCount": 0,
                    "mutatesLocalStateCount": 0,
                    "requiresCleanWorkspaceCount": 0,
                    "outputTargetCount": 0,
                    "profileTargetCount": 0,
                    "usageTargetCount": 0,
                    "mutationFlagCount": 0,
                    "outputTargets": [],
                    "profileTargets": [],
                    "usageTargets": [],
                    "mutationFlags": [],
                },
                "commandEffectReview": {
                    "level": "clear",
                    "requiresOperatorReview": False,
                    "headline": "No command target or mutation flag exposure detected.",
                    "checklist": [
                        "No command target or mutation flag exposure detected.",
                    ],
                    "gatePhaseSummary": {
                        "count": 1,
                        "requiredCount": 1,
                        "optionalCount": 0,
                        "phases": ["refresh"],
                        "hasBefore": False,
                        "hasAfter": False,
                        "hasRefresh": True,
                    },
                    "gateRunbook": {
                        "before": [],
                        "after": [],
                        "refresh": [
                            {
                                "phase": "refresh",
                                "label": "Refresh focused agent backlog after review",
                                "command": agent_backlog_refresh_command,
                                "commandArgs": agent_backlog_refresh_args,
                                "required": True,
                            },
                        ],
                        "other": [],
                    },
                    "gateCommands": [
                        {
                            "phase": "refresh",
                            "label": "Refresh focused agent backlog after review",
                            "command": agent_backlog_refresh_command,
                            "commandArgs": agent_backlog_refresh_args,
                            "required": True,
                        },
                    ],
                },
                "operatorRunbook": {
                    "version": 1,
                    "stageCount": 4,
                    "commandCount": 2,
                    "requiredCommandCount": 2,
                    "reviewLevel": "clear",
                    "requiresOperatorReview": False,
                    "phases": ["before", "execute", "after", "refresh"],
                    "nextStage": "execute",
                    "nextCommandLabel": "Run agent-skill-proposal-preview",
                    "nextCommand": "design-ai learn --propose-skills --json",
                    "nextCommandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                    "nextCommandRequired": True,
                    "nextCommandRunPolicy": "preview-only",
                    "nextCommandSelection": {
                        "strategy": "first-command-in-operator-runbook-stage-order",
                        "stageOrder": ["before", "execute", "after", "refresh"],
                        "stage": "execute",
                        "label": "Run agent-skill-proposal-preview",
                        "command": "design-ai learn --propose-skills --json",
                        "commandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                        "actionId": "agent-skill-proposal-preview",
                        "rank": 1,
                        "required": True,
                        "runPolicy": "preview-only",
                        "reason": "Selected the first command in the execute stage using operator runbook stage order.",
                    },
                    "stages": [
                        {
                            "phase": "before",
                            "label": "Run before executing backlog commands",
                            "commandCount": 0,
                            "requiredCount": 0,
                            "commands": [],
                        },
                        {
                            "phase": "execute",
                            "label": "Execute reviewed backlog commands",
                            "commandCount": 1,
                            "requiredCount": 1,
                            "commands": [
                                {
                                    "phase": "execute",
                                    "rank": 1,
                                    "actionId": "agent-skill-proposal-preview",
                                    "label": "Run agent-skill-proposal-preview",
                                    "command": "design-ai learn --propose-skills --json",
                                    "commandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                                    "required": True,
                                    "safetyLevel": "read-only",
                                    "runPolicy": "preview-only",
                                    "requiresReviewBeforeMutation": False,
                                },
                            ],
                        },
                        {
                            "phase": "after",
                            "label": "Run after executing backlog commands",
                            "commandCount": 0,
                            "requiredCount": 0,
                            "commands": [],
                        },
                        {
                            "phase": "refresh",
                            "label": "Refresh backlog status after execution",
                            "commandCount": 1,
                            "requiredCount": 1,
                            "commands": [
                                {
                                    "phase": "refresh",
                                    "label": "Refresh focused agent backlog after review",
                                    "command": agent_backlog_refresh_command,
                                    "commandArgs": agent_backlog_refresh_args,
                                    "required": True,
                                },
                            ],
                        },
                    ],
                },
                "ordered": [
                    {
                        "rank": 1,
                        "actionId": "agent-skill-proposal-preview",
                        "priority": "p2",
                        "category": "skill-evolution",
                        "title": "Preview skill instruction deltas from repeated check-capture signals.",
                        "command": "design-ai learn --propose-skills --json",
                        "commandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                        "safetyLevel": "read-only",
                        "runPolicy": "preview-only",
                        "commandEffects": {
                            "writesLocalFiles": False,
                            "mutatesLocalState": False,
                            "requiresCleanWorkspace": False,
                            "detectedFlags": [],
                            "mutationFlags": [],
                            "outputTargets": [],
                            "profileTargets": [],
                            "usageTargets": [],
                            "reviewReason": "Command is preview/report oriented and has no detected mutation flags.",
                        },
                        "requiresReviewBeforeMutation": False,
                    },
                ],
                "commandManifest": [
                    {
                        "rank": 1,
                        "actionId": "agent-skill-proposal-preview",
                        "command": "design-ai learn --propose-skills --json",
                        "commandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                        "safetyLevel": "read-only",
                        "runPolicy": "preview-only",
                        "commandEffects": {
                            "writesLocalFiles": False,
                            "mutatesLocalState": False,
                            "requiresCleanWorkspace": False,
                            "detectedFlags": [],
                            "mutationFlags": [],
                            "outputTargets": [],
                            "profileTargets": [],
                            "usageTargets": [],
                            "reviewReason": "Command is preview/report oriented and has no detected mutation flags.",
                        },
                        "requiresReviewBeforeMutation": False,
                    },
                ],
                "preview": [
                    {
                        "rank": 1,
                        "actionId": "agent-skill-proposal-preview",
                        "priority": "p2",
                        "category": "skill-evolution",
                        "title": "Preview skill instruction deltas from repeated check-capture signals.",
                        "command": "design-ai learn --propose-skills --json",
                        "commandArgs": ["design-ai", "learn", "--propose-skills", "--json"],
                        "safetyLevel": "read-only",
                        "runPolicy": "preview-only",
                        "commandEffects": {
                            "writesLocalFiles": False,
                            "mutatesLocalState": False,
                            "requiresCleanWorkspace": False,
                            "detectedFlags": [],
                            "mutationFlags": [],
                            "outputTargets": [],
                            "profileTargets": [],
                            "usageTargets": [],
                            "reviewReason": "Command is preview/report oriented and has no detected mutation flags.",
                        },
                        "requiresReviewBeforeMutation": False,
                    },
                ],
                "fileWriteReview": [],
                "mutationReview": [],
            },
            "verification": [
                {
                    "label": "Refresh signal registry JSON",
                    "command": "design-ai learn --signals --from-file . --json",
                },
                {
                    "label": "Save signal registry Markdown handoff",
                    "command": "design-ai learn --signals --from-file . --report --out learning-signals.md",
                },
                {
                    "label": "Gate focused agent backlog",
                    "command": agent_backlog_refresh_command,
                    "commandArgs": agent_backlog_refresh_args,
                },
            ],
            "boundaries": {
                "reportMutatesProfile": False,
                "reportMutatesSkillFiles": False,
                "reportCallsExternalAiApis": False,
                "generatedFromLocalSignals": True,
            },
        },
        "readiness": {
            "version": 1,
            "status": "pass",
            "summary": "Required and optional local learning signal surfaces are complete.",
            "requiredPassCount": 4,
            "requiredCount": 4,
            "requiredReady": True,
            "blockingCount": 0,
            "optionalGapCount": 0,
            "blockingChecks": [],
            "optionalGaps": [],
            "optionalGapDetails": [],
            "requiredCheckIds": ["learning-profile", "eval-signals", "workspace-readiness", "agent-development"],
            "optionalCheckIds": ["usage-sidecar", "check-capture"],
            "checkStatusById": {
                "learning-profile": "pass",
                "usage-sidecar": "pass",
                "eval-signals": "pass",
                "check-capture": "pass",
                "workspace-readiness": "pass",
                "agent-development": "pass",
            },
            "checkRequiredById": {
                "learning-profile": True,
                "usage-sidecar": False,
                "eval-signals": True,
                "check-capture": False,
                "workspace-readiness": True,
                "agent-development": True,
            },
            "checkCountByStatus": {
                "pass": 6,
                "info": 0,
                "warn": 0,
                "fail": 0,
                "missing": 0,
                "template": 0,
                "unknown": 0,
            },
            "requiredCheckCountByStatus": {
                "pass": 4,
                "info": 0,
                "warn": 0,
                "fail": 0,
                "missing": 0,
                "template": 0,
                "unknown": 0,
            },
            "optionalCheckCountByStatus": {
                "pass": 2,
                "info": 0,
                "warn": 0,
                "fail": 0,
                "missing": 0,
                "template": 0,
                "unknown": 0,
            },
            "checks": [
                {
                    "id": "learning-profile",
                    "label": "Learning profile",
                    "status": "pass",
                    "required": True,
                    "summary": "Profile has 3 entries with 0 audit failure(s) and 0 warning(s).",
                    "evidence": {"entries": 3},
                },
                {
                    "id": "usage-sidecar",
                    "label": "Usage sidecar",
                    "status": "pass",
                    "required": False,
                    "summary": "Usage sidecar has 2 event(s) and 0 stale selected id(s).",
                    "evidence": {"events": 2},
                },
                {
                    "id": "eval-signals",
                    "label": "Eval signals",
                    "status": "pass",
                    "required": True,
                    "summary": "Eval signals include 1 report(s), 0 unresolved template(s), 0 failed report(s), and 0 warned report(s).",
                    "evidence": {"files": 1},
                },
                {
                    "id": "check-capture",
                    "label": "Check learning capture",
                    "status": "pass",
                    "required": False,
                    "summary": "Profile includes 1 check-capture learning entry.",
                    "evidence": {"entries": 1},
                },
                {
                    "id": "workspace-readiness",
                    "label": "Workspace readiness",
                    "status": "pass",
                    "required": True,
                    "summary": "Workspace has 0 fail action(s), 0 warn action(s), and 0 total next action(s).",
                    "evidence": {"nextActionCount": 0},
                },
                {
                    "id": "agent-development",
                    "label": "Agent development backlog",
                    "status": "pass",
                    "required": True,
                    "summary": "Agent backlog has 1 action(s): 0 P0, 0 P1, 1 P2, 0 P3.",
                    "evidence": {"actions": 1},
                },
            ],
        },
        "commands": {
            "signalsJson": "design-ai learn --signals --from-file . --json",
            "signalsReport": "design-ai learn --signals --from-file . --report --out learning-signals.md",
        },
        "recommendations": [],
        "privacy": {
            "mutatesProfile": False,
            "mutatesSkillFiles": False,
            "callsExternalAiApis": False,
            "storesRawBriefText": False,
            "readsSignalFilesOnly": True,
        },
    }
    assert_agent_backlog_report_json(
        json.dumps(learning_agent_backlog_payload),
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        context=context,
        cmd=learn_agent_backlog_cmd,
        require_status_pass=True,
    )
    return learning_agent_backlog_payload


def _self_test_learn_proposal_reports(agent_backlog_refresh_args, agent_backlog_refresh_command, context, learn_agent_backlog_cmd, learning_agent_backlog_payload, learning_profile_path, learning_usage_path, tmp):
    """Package smoke self-test: learn skill-proposal report contracts."""
    missing_readiness_payload = json.loads(json.dumps(learning_agent_backlog_payload))
    missing_readiness_payload.pop("readiness", None)
    expect_self_test_failure(
        lambda: assert_agent_backlog_report_json(
            json.dumps(missing_readiness_payload),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="learn agent backlog JSON should include signal readiness summary with optional gap details, check index, and status count index",
        scope="package smoke",
    )
    no_command_agent_backlog_payload = {
        "version": 1,
        "generatedAt": "2026-06-02T00:00:06.000Z",
        "status": "pass",
        "signalStatus": "pass",
        "file": str(learning_profile_path),
        "usageFile": str(learning_usage_path),
        "signalSource": str(Path(tmp)),
        "counts": {
            "actions": 0,
            "p0": 0,
            "p1": 0,
            "p2": 0,
            "p3": 0,
            "learningEntries": 3,
            "usageEvents": 2,
            "evalSignals": 1,
            "checkCaptures": 0,
            "workspaceNextActions": 0,
        },
        "actions": [],
        "actionPlan": {
            "version": 1,
            "stepCount": 0,
            "nextStep": None,
            "steps": [],
            "safetySummary": {
                "total": 0,
                "readOnly": 0,
                "writesLocalFile": 0,
                "mutatesLocalState": 0,
                "requiresCleanWorkspace": 0,
                "requiresReviewBeforeMutation": 0,
            },
            "executionQueue": {
                "orderedCount": 0,
                "commandManifestCount": 0,
                "previewCount": 0,
                "fileWriteReviewCount": 0,
                "mutationReviewCount": 0,
                "nextActionId": "",
                "nextCommand": "",
                "nextCommandArgs": [],
                "nextCommandRunPolicy": "",
                "nextCommandSelection": {
                    "strategy": "first-command-in-safety-ordered-queue",
                    "safetyOrder": ["read-only", "writes-local-file", "mutates-local-state"],
                    "actionId": "",
                    "rank": None,
                    "safetyLevel": "",
                    "runPolicy": "",
                    "planNextActionId": "",
                    "planNextActionRank": None,
                    "matchesPlanNextAction": False,
                    "reason": "No command-bearing backlog action is available.",
                },
                "nextCommandAlignment": {
                    "strategy": "compare-operator-runbook-next-command-to-execution-queue-next-command",
                    "operatorStage": "refresh",
                    "operatorActionId": "",
                    "operatorCommand": agent_backlog_refresh_command,
                    "operatorCommandArgs": agent_backlog_refresh_args,
                    "queueActionId": "",
                    "queueCommand": "",
                    "queueCommandArgs": [],
                    "rankedNextActionId": "",
                    "matchesQueueNextCommand": False,
                    "matchesQueueNextAction": False,
                    "operatorRunsBeforeQueueCommand": False,
                    "queueMatchesRankedNextAction": False,
                    "reason": EXPECTED_AGENT_BACKLOG_EMPTY_QUEUE_ALIGNMENT_REASON,
                },
                "operatorHandoff": {
                    "version": 1,
                    "decision": "none",
                    "state": {
                        "version": 1,
                        "status": "no-command",
                        "ready": True,
                        "hasCommand": False,
                        "complete": True,
                        "canRunWithoutReview": False,
                        "requiresGate": False,
                        "requiresRefresh": False,
                        "summary": "Focused agent backlog is clear; no handoff command is required.",
                    },
                    "source": "",
                    "phase": "",
                    "label": "",
                    "command": "",
                    "commandArgs": [],
                    "actionId": "",
                    "rank": None,
                    "runPolicy": "",
                    "required": False,
                    "isGate": False,
                    "nextQueueActionId": "",
                    "nextQueueCommand": "",
                    "nextQueueCommandArgs": [],
                    "nextQueueCommandRequiresGate": False,
                    "operatorGateAppliesToNextQueueAction": False,
                    "nextQueueActionBlockedByGate": False,
                    "refreshCommand": agent_backlog_refresh_command,
                    "refreshCommandArgs": agent_backlog_refresh_args,
                    "refreshCommandLabel": "Refresh focused agent backlog after review",
                    "refreshCommandRequired": False,
                    "reviewLevel": "clear",
                    "requiresOperatorReview": False,
                    "reason": EXPECTED_AGENT_BACKLOG_NO_COMMAND_HANDOFF_REASON,
                },
                "commandEffectReview": {
                    "level": "clear",
                    "requiresOperatorReview": False,
                    "headline": "No command target or mutation flag exposure detected.",
                    "checklist": ["No command target or mutation flag exposure detected."],
                    "gatePhaseSummary": {
                        "count": 1,
                        "requiredCount": 0,
                        "optionalCount": 1,
                        "phases": ["refresh"],
                        "hasBefore": False,
                        "hasAfter": False,
                        "hasRefresh": True,
                    },
                    "gateRunbook": {
                        "before": [],
                        "after": [],
                        "refresh": [
                            {
                                "phase": "refresh",
                                "label": "Refresh focused agent backlog after review",
                                "command": agent_backlog_refresh_command,
                                "commandArgs": agent_backlog_refresh_args,
                                "required": False,
                            },
                        ],
                        "other": [],
                    },
                    "gateCommands": [
                        {
                            "phase": "refresh",
                            "label": "Refresh focused agent backlog after review",
                            "command": agent_backlog_refresh_command,
                            "commandArgs": agent_backlog_refresh_args,
                            "required": False,
                        },
                    ],
                },
                "operatorRunbook": {
                    "version": 1,
                    "stageCount": 4,
                    "commandCount": 1,
                    "requiredCommandCount": 0,
                    "reviewLevel": "clear",
                    "requiresOperatorReview": False,
                    "phases": ["before", "execute", "after", "refresh"],
                    "nextStage": "refresh",
                    "nextCommandLabel": "Refresh focused agent backlog after review",
                    "nextCommand": agent_backlog_refresh_command,
                    "nextCommandArgs": agent_backlog_refresh_args,
                    "nextCommandRequired": False,
                    "nextCommandRunPolicy": "",
                    "nextCommandSelection": {
                        "strategy": "first-command-in-operator-runbook-stage-order",
                        "stageOrder": ["before", "execute", "after", "refresh"],
                        "stage": "refresh",
                        "label": "Refresh focused agent backlog after review",
                        "command": agent_backlog_refresh_command,
                        "commandArgs": agent_backlog_refresh_args,
                        "actionId": "",
                        "rank": None,
                        "required": False,
                        "runPolicy": "",
                        "reason": EXPECTED_AGENT_BACKLOG_REFRESH_ONLY_RUNBOOK_REASON,
                    },
                },
                "ordered": [],
                "commandManifest": [],
                "preview": [],
                "fileWriteReview": [],
                "mutationReview": [],
            },
            "verification": [
                {
                    "label": "Gate focused agent backlog",
                    "command": agent_backlog_refresh_command,
                    "commandArgs": agent_backlog_refresh_args,
                },
            ],
            "boundaries": {
                "reportMutatesProfile": False,
                "reportMutatesSkillFiles": False,
                "reportCallsExternalAiApis": False,
                "generatedFromLocalSignals": True,
            },
        },
        "readiness": {
            "version": 1,
            "status": "pass",
            "summary": "Required local learning signal surfaces are ready; optional evidence gaps remain.",
            "requiredPassCount": 4,
            "requiredCount": 4,
            "requiredReady": True,
            "blockingCount": 0,
            "optionalGapCount": 1,
            "blockingChecks": [],
            "optionalGaps": ["check-capture"],
            "optionalGapDetails": [
                {
                    "id": "check-capture",
                    "label": "Check learning capture",
                    "status": "info",
                    "summary": "No check-capture entries are present; this is advisory until real warn/fail checks are captured.",
                    "reason": EXPECTED_CHECK_CAPTURE_OPTIONAL_GAP_REASON,
                    "nextCondition": EXPECTED_CHECK_CAPTURE_OPTIONAL_GAP_NEXT_CONDITION,
                    "automationPolicy": EXPECTED_CHECK_CAPTURE_OPTIONAL_GAP_AUTOMATION_POLICY,
                },
            ],
            "requiredCheckIds": ["learning-profile", "eval-signals", "workspace-readiness", "agent-development"],
            "optionalCheckIds": ["usage-sidecar", "check-capture"],
            "checkStatusById": {
                "learning-profile": "pass",
                "usage-sidecar": "pass",
                "eval-signals": "pass",
                "check-capture": "info",
                "workspace-readiness": "pass",
                "agent-development": "pass",
            },
            "checkRequiredById": {
                "learning-profile": True,
                "usage-sidecar": False,
                "eval-signals": True,
                "check-capture": False,
                "workspace-readiness": True,
                "agent-development": True,
            },
            "checkCountByStatus": {
                "pass": 5,
                "info": 1,
                "warn": 0,
                "fail": 0,
                "missing": 0,
                "template": 0,
                "unknown": 0,
            },
            "requiredCheckCountByStatus": {
                "pass": 4,
                "info": 0,
                "warn": 0,
                "fail": 0,
                "missing": 0,
                "template": 0,
                "unknown": 0,
            },
            "optionalCheckCountByStatus": {
                "pass": 1,
                "info": 1,
                "warn": 0,
                "fail": 0,
                "missing": 0,
                "template": 0,
                "unknown": 0,
            },
            "checks": [
                {
                    "id": "learning-profile",
                    "label": "Learning profile",
                    "status": "pass",
                    "required": True,
                    "summary": "Profile has 3 entries with 0 audit failure(s) and 0 warning(s).",
                    "evidence": {"entries": 3},
                },
                {
                    "id": "usage-sidecar",
                    "label": "Usage sidecar",
                    "status": "pass",
                    "required": False,
                    "summary": "Usage sidecar has 2 event(s) and 0 stale selected id(s).",
                    "evidence": {"events": 2},
                },
                {
                    "id": "eval-signals",
                    "label": "Eval signals",
                    "status": "pass",
                    "required": True,
                    "summary": "Eval signals include 1 report(s), 0 unresolved template(s), 0 failed report(s), and 0 warned report(s).",
                    "evidence": {"files": 1},
                },
                {
                    "id": "check-capture",
                    "label": "Check learning capture",
                    "status": "info",
                    "required": False,
                    "summary": "No check-capture entries are present; this is advisory until real warn/fail checks are captured.",
                    "evidence": {"entries": 0},
                },
                {
                    "id": "workspace-readiness",
                    "label": "Workspace readiness",
                    "status": "pass",
                    "required": True,
                    "summary": "Workspace has 0 fail action(s), 0 warn action(s), and 0 total next action(s).",
                    "evidence": {"nextActionCount": 0},
                },
                {
                    "id": "agent-development",
                    "label": "Agent development backlog",
                    "status": "pass",
                    "required": True,
                    "summary": "Agent backlog has 0 action(s): 0 P0, 0 P1, 0 P2, 0 P3.",
                    "evidence": {"actions": 0},
                },
            ],
        },
        "commands": {
            "signalsJson": "design-ai learn --signals --from-file . --json",
            "signalsReport": "design-ai learn --signals --from-file . --report --out learning-signals.md",
            "agentBacklogJson": agent_backlog_refresh_command,
            "agentBacklogJsonArgs": agent_backlog_refresh_args,
        },
        "recommendations": [],
        "privacy": {
            "mutatesProfile": False,
            "mutatesSkillFiles": False,
            "callsExternalAiApis": False,
            "storesRawBriefText": False,
            "readsSignalFilesOnly": True,
        },
    }
    assert_agent_backlog_no_command_json(
        json.dumps(no_command_agent_backlog_payload),
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        context=context,
        cmd=learn_agent_backlog_cmd,
    )
    no_command_agent_backlog_markdown = "\n".join([
        "# Agent Development Backlog Report",
        "",
        f"- Learning file: {learning_profile_path}",
        f"- Usage file: {learning_usage_path}",
        "## Summary",
        "- Actions: 0",
        "- Check captures: 0",
        "## Signal Readiness",
        "- Required ready: yes",
        "- Required checks: 4/4",
        "- Blocking checks: 0",
        "- Optional gaps: 1",
        "Readiness check index:",
        "- Required ids: learning-profile, eval-signals, workspace-readiness, agent-development",
        "- Optional ids: usage-sidecar, check-capture",
        "- Status index: learning-profile=pass, usage-sidecar=pass, eval-signals=pass, check-capture=info, workspace-readiness=pass, agent-development=pass",
        "- Required index: learning-profile=yes, usage-sidecar=no, eval-signals=yes, check-capture=no, workspace-readiness=yes, agent-development=yes",
        "- Status counts: pass=5, info=1, warn=0, fail=0, missing=0, template=0, unknown=0",
        "- Required status counts: pass=4, info=0, warn=0, fail=0, missing=0, template=0, unknown=0",
        "- Optional status counts: pass=1, info=1, warn=0, fail=0, missing=0, template=0, unknown=0",
        "Readiness checks:",
        "- check-capture [optional] info: No check-capture entries are present; this is advisory until real warn/fail checks are captured.",
        "- agent-development [required] pass: Agent backlog has 0 action(s): 0 P0, 0 P1, 0 P2, 0 P3.",
        "Optional gap details:",
        f"- check-capture: {EXPECTED_CHECK_CAPTURE_OPTIONAL_GAP_REASON}",
        f"  Next condition: {EXPECTED_CHECK_CAPTURE_OPTIONAL_GAP_NEXT_CONDITION}",
        f"  Automation policy: {EXPECTED_CHECK_CAPTURE_OPTIONAL_GAP_AUTOMATION_POLICY}",
        "## Backlog Actions",
        "No agent development backlog actions emitted.",
        "## Action Plan",
        "Safety summary:",
        "- Read-only: 0",
        "- Writes local file: 0",
        "- Mutates local state: 0",
        "Execution queue:",
        "- Preview/read-only commands: 0",
        "- Local file-write review commands: 0",
        "- Local mutation review commands: 0",
        "- Ordered commands: 0",
        "- Command manifest entries: 0",
        "- Command effect review: No command target or mutation flag exposure detected.",
        "- Operator runbook: 4 stage(s), 1 command(s), 0 required",
        f"- Operator next command: refresh: `{agent_backlog_refresh_command}`",
        "- Operator next command selection: first-command-in-operator-runbook-stage-order",
        "- Recommended next command selection: first-command-in-safety-ordered-queue",
        "- Operator/queue next command alignment: different",
        "- Operator handoff state: no-command; ready yes; can run without review no; refresh optional",
        "- Operator handoff summary: Focused agent backlog is clear; no handoff command is required.",
        f"- Operator handoff refresh: {agent_backlog_refresh_command}",
        "No execution steps emitted.",
        "## Follow-Up Commands",
        "design-ai learn --signals --from-file . --json",
        "## Privacy And Boundaries",
        "- Mutates learning profile: no",
        "- Mutates skill files: no",
        "- Calls external AI APIs: no",
        "This report is read-only evidence",
    ])
    assert_agent_backlog_no_command_report_markdown(
        no_command_agent_backlog_markdown,
        profile_path=learning_profile_path,
        usage_path=learning_usage_path,
        context=context,
        cmd=[*learn_agent_backlog_cmd[:-1], "--report"],
    )
    expect_self_test_failure(
        lambda: assert_agent_backlog_no_command_report_markdown(
            no_command_agent_backlog_markdown.replace("Optional gap details:", "Optional evidence details:"),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=[*learn_agent_backlog_cmd[:-1], "--report"],
        ),
        expected="no-command learn agent backlog Markdown report missing 'Optional gap details:'",
        scope="package smoke",
    )
    expect_self_test_failure(
        lambda: assert_agent_backlog_no_command_report_markdown(
            no_command_agent_backlog_markdown.replace("Readiness check index:", "Readiness check summary:"),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=[*learn_agent_backlog_cmd[:-1], "--report"],
        ),
        expected="no-command learn agent backlog Markdown report missing 'Readiness check index:'",
        scope="package smoke",
    )
    optional_gap_detail_drift_payload = json.loads(json.dumps(no_command_agent_backlog_payload))
    optional_gap_detail_drift_payload["readiness"].pop("optionalGapDetails", None)
    expect_self_test_failure(
        lambda: assert_agent_backlog_no_command_json(
            json.dumps(optional_gap_detail_drift_payload),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="learn agent backlog JSON should include signal readiness summary with optional gap details, check index, and status count index",
        scope="package smoke",
    )
    check_index_drift_payload = json.loads(json.dumps(no_command_agent_backlog_payload))
    check_index_drift_payload["readiness"].pop("checkStatusById", None)
    expect_self_test_failure(
        lambda: assert_agent_backlog_no_command_json(
            json.dumps(check_index_drift_payload),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="learn agent backlog JSON should include signal readiness summary with optional gap details, check index, and status count index",
        scope="package smoke",
    )
    check_count_index_drift_payload = json.loads(json.dumps(no_command_agent_backlog_payload))
    check_count_index_drift_payload["readiness"].pop("checkCountByStatus", None)
    expect_self_test_failure(
        lambda: assert_agent_backlog_no_command_json(
            json.dumps(check_count_index_drift_payload),
            profile_path=learning_profile_path,
            usage_path=learning_usage_path,
            context=context,
            cmd=learn_agent_backlog_cmd,
        ),
        expected="learn agent backlog JSON should include signal readiness summary with optional gap details, check index, and status count index",
        scope="package smoke",
    )
    refresh_reason_drift_payload = json.loads(json.dumps(no_command_agent_backlog_payload))
    refresh_reason_drift_payload["actionPlan"]["executionQueue"]["operatorRunbook"]["nextCommandSelection"]["reason"] = (
        "Selected the first command in the refresh stage using operator runbook stage order."
    )
    return refresh_reason_drift_payload
