from __future__ import annotations

from pathlib import Path

from smoke_assertions import assert_no_ansi, format_cmd


def require_package_smoke(
    condition: bool, *, context: str, cmd: list[str], message: str
) -> None:
    if not condition:
        raise SystemExit(f"{context}: {message}\ncommand: {format_cmd(cmd)}")


def assert_skill_proposal_apply_plan_markdown(
    raw: str,
    *,
    profile_path: Path,
    usage_path: Path,
    review_path: Path,
    context: str,
    cmd: list[str],
) -> None:
    assert_no_ansi(raw, cmd)
    for expected in (
        "# Skill Proposal Apply Plan",
        "- Status: warn",
        "- Proposal status:",
        "- Signal status:",
        f"- File: {profile_path}",
        f"- Usage sidecar: {usage_path}",
        f"- Review file: {review_path}",
        "- Accepted proposals: 1",
        "## Manual Apply Tasks",
        "skills/component-spec-writer/SKILL.md",
        "After the skill edit and verification pass, update the review decision from `accepted` to `applied`.",
        "## Follow-up Commands",
        "--review-check --json",
        "## Command Contract",
        "- Valid: yes",
        "- Required keys: reviewCheckJson, reviewCheckReport, proposalPatchPreview, strictGate",
        "- Check count: 18",
        "- Pass count: 18",
        "- Warning count: 0",
        "- Failure count: 0",
        "- Failed checks: none",
        "- Next command key: reviewCheckJson",
        "- Next command policy: preview-only",
        "- Next command safety: read-only",
        "- Next command: `design-ai learn --propose-skills",
        "- Command sequence count: 4",
        "- Command sequence policy: mixed-preview-local-output",
        "- Command sequence executable: yes",
        "- Command sequence local outputs: 2",
        "- Command sequence mutates profile: no",
        "- Command sequence mutates review file: no",
        "- Command sequence mutates skill files: no",
        "- Command sequence calls external AI APIs: no",
        "- Operator runbook stages: 4",
        "- Operator runbook keys: previewArtifacts, manualSkillEdit, reviewReadiness, strictGate",
        "- Operator runbook required stages: 3",
        "- Operator runbook next stage: previewArtifacts",
        "- Operator runbook next required stage: manualSkillEdit",
        "- Operator runbook next required command stage: reviewReadiness",
        "- Operator runbook stage selection: optional-preview-before-required-manual-edit",
        "- Operator runbook decision: offer-optional-preview",
        "- Operator runbook decision safety: local-output",
        "- Operator runbook decision commands: reviewCheckReport, proposalPatchPreview",
        "- Operator runbook decision next command: reviewCheckReport",
        "- Operator runbook selected stage: previewArtifacts (optional, local-output-preview)",
        "Command sequence:",
        "- 1. reviewCheckJson (preview-only / read-only): `design-ai learn --propose-skills",
        "- 2. reviewCheckReport (output-artifact / local-output): `design-ai learn --propose-skills",
        "- 3. proposalPatchPreview (output-artifact / local-output): `design-ai learn --propose-skills",
        "- 4. strictGate (strict-readiness-gate / read-only): `design-ai learn --propose-skills",
        "Operator runbook:",
        "- 1. previewArtifacts (optional / local-output-preview): reviewCheckReport, proposalPatchPreview",
        "- 2. manualSkillEdit (required / manual-review): manual",
        "- 3. reviewReadiness (required / read-only-check): reviewCheckJson",
        "- 4. strictGate (required / read-only-gate): strictGate",
        "- Next action: Run reviewCheckJson after manual skill edits, then use strictGate before marking proposals applied.",
        "## Privacy And Boundaries",
        "- Mutates learning profile: no",
        "- Mutates review file: no",
        "- Mutates skill files: no",
        "- Calls external AI APIs: no",
    ):
        require_package_smoke(
            expected in raw,
            context=context,
            cmd=cmd,
            message=f"learn skill proposal apply-plan Markdown report missing {expected!r}",
        )


def assert_skill_proposal_apply_plan_human(
    raw: str,
    *,
    context: str,
    cmd: list[str],
) -> None:
    assert_no_ansi(raw, cmd)
    for expected in (
        "Skill proposal apply plan",
        "Manual apply tasks:",
        "Follow-up commands:",
        "Command contract:",
        "- valid: yes",
        "- status: pass",
        "- required keys: reviewCheckJson, reviewCheckReport, proposalPatchPreview, strictGate",
        "- forbidden flags: --yes",
        "- check count: 18",
        "- pass count: 18",
        "- warning count: 0",
        "- failure count: 0",
        "- failed checks: none",
        "- next command key: reviewCheckJson",
        "- next command policy: preview-only",
        "- next command safety: read-only",
        "- next command: design-ai learn --propose-skills",
        "- command sequence count: 4",
        "- command sequence policy: mixed-preview-local-output",
        "- command sequence executable: yes",
        "- command sequence local outputs: 2",
        "- command sequence mutates profile: no",
        "- command sequence mutates review file: no",
        "- command sequence mutates skill files: no",
        "- command sequence calls external AI APIs: no",
        "- operator runbook stages: 4",
        "- operator runbook keys: previewArtifacts, manualSkillEdit, reviewReadiness, strictGate",
        "- operator runbook required stages: 3",
        "- operator runbook next stage: previewArtifacts",
        "- operator runbook next required stage: manualSkillEdit",
        "- operator runbook next required command stage: reviewReadiness",
        "- operator runbook stage selection: optional-preview-before-required-manual-edit",
        "- operator runbook decision: offer-optional-preview",
        "- operator runbook decision safety: local-output",
        "- operator runbook decision commands: reviewCheckReport, proposalPatchPreview",
        "- operator runbook decision next command: reviewCheckReport",
        "- operator runbook selected stage: previewArtifacts (optional, local-output-preview)",
        "Command sequence:",
        "- 1. reviewCheckJson: preview-only / read-only",
        "- 2. reviewCheckReport: output-artifact / local-output",
        "- 3. proposalPatchPreview: output-artifact / local-output",
        "- 4. strictGate: strict-readiness-gate / read-only",
        "Operator runbook:",
        "- 1. previewArtifacts: optional / local-output-preview / reviewCheckReport, proposalPatchPreview",
        "- 2. manualSkillEdit: required / manual-review / manual",
        "- 3. reviewReadiness: required / read-only-check / reviewCheckJson",
        "- 4. strictGate: required / read-only-gate / strictGate",
        "- next action: Run reviewCheckJson after manual skill edits, then use strictGate before marking proposals applied.",
        "Privacy: apply plan is read-only",
    ):
        require_package_smoke(
            expected in raw,
            context=context,
            cmd=cmd,
            message=f"learn skill proposal apply-plan human output missing {expected!r}",
        )
