// Help text for `design-ai learn`.

import { LEARNING_FEEDBACK_OUTCOMES } from "../lib/learn.mjs";

export function printHelp() {
  console.log("Usage:  design-ai learn [--list] [--category kind] [--query text] [--explain] [--limit N] [--json] [--out file] [--force]");
  console.log("        design-ai learn --init [--yes|--dry-run] [--json] [--out file] [--force]");
  console.log("        design-ai learn --remember text [--category kind] [--json] [--out file] [--force]");
  console.log("        design-ai learn --feedback text [--outcome keep|improve|avoid] [--category kind] [--json] [--out file] [--force]");
  console.log("        design-ai learn --feedback --from-file notes.md [--outcome keep|improve|avoid] [--category kind] [--json] [--out file] [--force]");
  console.log("        cat notes.md | design-ai learn --feedback --stdin [--outcome keep|improve|avoid] [--category kind] [--json] [--out file] [--force]");
  console.log("        design-ai learn --from-file notes.md [--category kind] [--json] [--out file] [--force]");
  console.log("        cat notes.md | design-ai learn --stdin [--category kind] [--json] [--out file] [--force]");
  console.log("        design-ai learn --export [--category kind] [--query text] [--limit N] [--json] [--out file] [--force]");
  console.log("        design-ai learn --backup [--json] [--out file] [--force]");
  console.log("        design-ai learn --redact [--json] [--out file] [--force]");
  console.log("        design-ai learn --redact --from-file learning-backup.json [--json] [--out file] [--force]");
  console.log("        cat learning-backup.json | design-ai learn --redact --stdin [--json] [--out file] [--force]");
  console.log("        design-ai learn --verify --from-file learning.json [--json] [--out file] [--force]");
  console.log("        cat learning.json | design-ai learn --verify --stdin [--json] [--out file] [--force]");
  console.log("        design-ai learn --diff --from-file learning.json [--json] [--out file] [--force]");
  console.log("        cat learning.json | design-ai learn --diff --stdin [--json] [--out file] [--force]");
  console.log("        design-ai learn --restore --from-file learning-backup.json [--dry-run|--yes] [--backup-file path] [--json] [--out file] [--force]");
  console.log("        cat learning-backup.json | design-ai learn --restore --stdin [--dry-run|--yes] [--backup-file path] [--json] [--out file] [--force]");
  console.log("        design-ai learn --restore-backups [--limit N] [--json] [--out file] [--force]");
  console.log("        design-ai learn --restore-backups --prune [--keep N] [--dry-run|--yes] [--json] [--out file] [--force]");
  console.log("        design-ai learn --import --from-file learning.json --dry-run [--json] [--out file] [--force]");
  console.log("        cat learning.json | design-ai learn --import --stdin --yes [--json] [--out file] [--force]");
  console.log("        design-ai learn --audit [--json] [--out file] [--force]");
  console.log("        design-ai learn --audit --fix --dry-run [--json] [--out file] [--force]");
  console.log("        design-ai learn --audit --fix --yes [--json] [--out file] [--force]");
  console.log("        design-ai learn --curate [--dry-run|--yes] [--usage-file path] [--json|--report] [--out file] [--force]");
  console.log("        design-ai learn --stats [--json] [--out file] [--force]");
  console.log("        design-ai learn --usage [--limit N] [--usage-file path] [--json] [--out file] [--force]");
  console.log("        design-ai learn --signals [--from-file signal-file-or-dir] [--usage-file path] [--strict] [--json|--report] [--out file] [--force]");
  console.log("        design-ai learn --agent-backlog [--from-file signal-file-or-dir] [--usage-file path] [--strict] [--json|--report] [--out file] [--force]");
  console.log("        design-ai learn --propose-skills [--from-file signal-file-or-dir] [--usage-file path] [--review-file path] [--review-check|--apply-plan] [--min-evidence N] [--strict] [--json|--report|--patch|--review-template] [--out file] [--force]");
  console.log("        design-ai learn --eval-template [--query text] [--category kind] [--limit N] [--json] [--out file] [--force]");
  console.log("        design-ai learn --eval --from-file eval.json [--category kind] [--limit N] [--strict] [--json] [--out file] [--force]");
  console.log("        cat eval.json | design-ai learn --eval --stdin [--category kind] [--limit N] [--strict] [--json]");
  console.log("        design-ai learn --forget id-or-number --yes [--json] [--out file] [--force]");
  console.log("        design-ai learn --clear --yes [--json] [--out file] [--force]\n");
  console.log("Stores local design preferences for explicit prompt personalization.");
  console.log("This is local memory, not model training or fine-tuning.\n");
  console.log("Options:");
  console.log("  --init               Preview or apply starter local learning entries for dogfood use");
  console.log("  --remember text      Remember an inline preference or project constraint");
  console.log("  --feedback text      Convert outcome feedback into a reusable local learning note");
  console.log(`  --outcome kind       Feedback outcome: ${LEARNING_FEEDBACK_OUTCOMES.join(", ")}. Default: improve`);
  console.log("  --from-file file     Read remember/feedback text or import/verify/diff/restore/redact JSON from a file");
  console.log("  --stdin              Read remember/feedback text or import/verify/diff/restore/redact JSON from standard input");
  console.log("  --category kind      preference, brand, workflow, constraint, accessibility, korean, other");
  console.log("  --query text         Filter list/export output to entries whose category or text matches the query");
  console.log("  --explain            With --list, include selection score, matched tokens, and reason");
  console.log("  --limit N            Limit list/export output to the N most recent matching entries, 1-100");
  console.log("  --list               List saved learning entries. Default when no action is given");
  console.log("  --export             Print the learned-context block used by --with-learning");
  console.log("  --backup             Print a full portable learning-profile backup; use --json for importable JSON");
  console.log("  --redact             Print a portable JSON backup with sensitive-looking text redacted");
  console.log("  --verify             Validate a portable learning JSON payload without importing it");
  console.log("  --diff               Compare the active profile against a portable learning JSON payload without importing it");
  console.log("  --restore            Preview or apply replacing the active profile with a portable learning JSON payload");
  console.log("  --restore-backups    List sibling restore rollback backups for the active learning profile");
  console.log("  --prune              With --restore-backups, preview or delete older rollback backup files");
  console.log("  --keep N             With --restore-backups --prune, keep the N newest backups. Default: 5");
  console.log("  --backup-file path   With --restore, override the automatic rollback backup file path");
  console.log("  --import             Merge entries from a JSON learning profile or learn --export --json payload");
  console.log("  --audit              Inspect profile shape, sensitive content, and cleanup suggestions without changing it");
  console.log("  --fix                With --audit, prepare or apply safe cleanup suggestions");
  console.log("  --curate             Preview or apply archive-first curation for duplicate/sensitive entries, plus usage review hints");
  console.log("  --report             With --curate, --signals, --agent-backlog, or --propose-skills, emit a Markdown review report instead of human console output");
  console.log("  --patch              With --propose-skills, emit a preview-only unified diff handoff without editing skill files");
  console.log("  --review-check       With --propose-skills, verify the review file against current proposals without changing files");
  console.log("  --apply-plan         With --propose-skills, turn accepted review decisions into a read-only manual apply plan");
  console.log("  --review-template    With --propose-skills, emit a JSON proposal review-file template without changing review decisions");
  console.log("  --dry-run            Preview --init, --import, --restore, --curate, --restore-backups --prune, or --audit --fix without changing files");
  console.log("  --stats              Summarize profile counts, recency, and audit status without changing it");
  console.log("  --usage              Summarize prompt/pack --with-learning usage sidecar events without changing files");
  console.log("  --signals            Summarize local learning, usage, eval, check-capture, agent backlog, and workspace readiness signals without changing files");
  console.log("  --agent-backlog      Emit a focused local AI/agent development backlog from the signal registry without changing files");
  console.log("  --propose-skills     Preview skill instruction deltas from repeated check-capture learning signals without changing files");
  console.log("  --min-evidence N     With --propose-skills, require N related check-capture entries before emitting a proposal. Default: 2");
  console.log("  --review-file path   With --propose-skills, read proposal review decisions without changing the review file");
  console.log("  --eval-template      Generate a runnable learning eval checkpoint from the active profile");
  console.log("  --eval               Run deterministic learning-selection checkpoint cases without changing files");
  console.log("  --strict             With --eval, --signals, --agent-backlog, or --propose-skills, exit non-zero when any checkpoint, signal, backlog, or proposal gate warns or fails");
  console.log("  --forget id-or-number Remove one entry by id or 1-based list number; requires --yes");
  console.log("  --clear              Remove all saved learning entries; requires --yes");
  console.log("  --yes                Confirm destructive local profile changes");
  console.log("  --file path          Override the learning profile path");
  console.log("  --usage-file path    Override the learning usage sidecar path used by --usage, --curate, --signals, --agent-backlog, or --propose-skills");
  console.log("  --json               Emit machine-readable output");
  console.log("  --out file           Write JSON output to a file, export Markdown for --export, or learning review report Markdown");
  console.log("  --force              Overwrite an existing --out file, or an existing --backup-file during --restore");
  console.log("");
  console.log("Environment:");
  console.log("  DESIGN_AI_LEARNING_FILE=/path/learning.json       Override the default profile path");
  console.log("  DESIGN_AI_LEARNING_USAGE_FILE=/path/usage.json    Override the default usage sidecar path");
  console.log("");
  console.log("Examples:");
  console.log("  design-ai learn --init");
  console.log("  design-ai learn --init --yes --json");
  console.log("  design-ai learn --remember \"Prefer dense Korean product UI\" --category korean");
  console.log("  design-ai learn --feedback \"Keep audit findings short and evidence-led\" --outcome keep");
  console.log("  design-ai learn --feedback --from-file feedback.md --outcome improve");
  console.log("  cat feedback.md | design-ai learn --feedback --stdin --outcome avoid --category brand");
  console.log("  design-ai learn --list --category korean --limit 5");
  console.log("  design-ai learn --list --query \"keyboard accessibility\" --explain --json");
  console.log("  design-ai learn --export --query \"pricing page\" --limit 3");
  console.log("  design-ai learn --backup --json --out learning-backup.json");
  console.log("  design-ai learn --redact --json --out learning-redacted.json");
  console.log("  design-ai learn --redact --from-file learning-backup.json --json --out learning-redacted.json --force");
  console.log("  design-ai learn --verify --from-file learning-backup.json");
  console.log("  design-ai learn --diff --from-file learning-backup.json --json");
  console.log("  design-ai learn --restore --from-file learning-backup.json --dry-run");
  console.log("  design-ai learn --restore --from-file learning-backup.json --yes --backup-file learning-before-restore.json");
  console.log("  design-ai learn --restore-backups --json");
  console.log("  design-ai learn --restore-backups --prune --keep 5");
  console.log("  design-ai learn --restore-backups --prune --keep 5 --yes");
  console.log("  design-ai learn --import --from-file learning.json --dry-run");
  console.log("  design-ai learn --audit");
  console.log("  design-ai learn --audit --fix --dry-run");
  console.log("  design-ai learn --curate");
  console.log("  design-ai learn --curate --usage-file ./learning.usage.json");
  console.log("  design-ai learn --curate --report --out learning-curation-report.md");
  console.log("  design-ai learn --curate --yes --json");
  console.log("  design-ai learn --stats --json");
  console.log("  design-ai learn --usage --json");
  console.log("  design-ai learn --signals --from-file . --json");
  console.log("  design-ai learn --signals --from-file . --report --out learning-signals.md");
  console.log("  design-ai learn --agent-backlog --from-file . --report --out agent-backlog.md");
  console.log("  design-ai learn --propose-skills --from-file . --min-evidence 3 --json");
  console.log("  design-ai learn --propose-skills --from-file . --strict --json");
  console.log("  design-ai learn --propose-skills --from-file . --review-file skill-proposals.review.json --strict --json");
  console.log("  design-ai learn --propose-skills --from-file . --review-file skill-proposals.review.json --review-check --json");
  console.log("  design-ai learn --propose-skills --from-file . --review-file skill-proposals.review.json --apply-plan --json");
  console.log("  design-ai learn --propose-skills --from-file . --review-template --out skill-proposals.review.json");
  console.log("  design-ai learn --propose-skills --from-file . --report --out skill-proposals.md");
  console.log("  design-ai learn --propose-skills --from-file . --patch --out skill-proposals.patch");
  console.log("  design-ai learn --eval-template --query \"keyboard accessibility\" --out learning-eval.json");
  console.log("  design-ai learn --eval --from-file learning-eval.json --strict --json");
  console.log("  design-ai learn --forget learn-abc123def0 --yes");
  console.log("  design-ai prompt \"audit checkout UX\" --with-learning");
  console.log("  design-ai pack \"spec a pricing page\" --with-learning");
}
