#!/usr/bin/env python3
"""
Generate CHANGELOG.md from git commit history.

Reads commits since the last tag (or all commits if no tags) and
formats them into a markdown changelog grouped by version.

Usage:
  python3 tools/audit/changelog-generate.py [--since vN] [--output CHANGELOG.md]

Categorizes commits by conventional-commit prefix:
  feat: → "Added"
  fix: → "Fixed"
  refactor: → "Changed"
  docs: → "Documentation"
  chore: → "Maintenance"
  perf: → "Performance"

Skips commits matching ^(chore: bump|chore: release).
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


CATEGORY_MAP = {
    "feat": "Added",
    "fix": "Fixed",
    "refactor": "Changed",
    "docs": "Documentation",
    "chore": "Maintenance",
    "perf": "Performance",
    "test": "Testing",
    "ci": "CI/CD",
    "build": "Build",
    "style": "Style",
    "revert": "Reverted",
}

SKIP_PATTERNS = [
    r"^chore:\s*bump",
    r"^chore:\s*release",
    r"^Merge\s+",
]


def run(cmd: list[str]) -> str:
    return subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT, check=True).stdout


def get_tags() -> list[str]:
    out = run(["git", "tag", "--sort=-creatordate"])
    return [t.strip() for t in out.splitlines() if t.strip()]


def get_commits_between(start: str | None, end: str = "HEAD") -> list[tuple[str, str, str]]:
    """Return (sha, subject, date) tuples."""
    if start:
        rev_range = f"{start}..{end}"
    else:
        rev_range = end
    out = run(["git", "log", "--pretty=format:%h|%s|%ad", "--date=short", rev_range])
    commits = []
    for line in out.splitlines():
        if not line.strip():
            continue
        parts = line.split("|", 2)
        if len(parts) == 3:
            commits.append((parts[0], parts[1], parts[2]))
    return commits


def should_skip(subject: str) -> bool:
    for pattern in SKIP_PATTERNS:
        if re.match(pattern, subject):
            return True
    return False


def categorize(subject: str) -> str:
    match = re.match(r"^(\w+)(?:\(([^)]+)\))?:\s*(.+)$", subject)
    if not match:
        return "Other"
    prefix = match.group(1).lower()
    return CATEGORY_MAP.get(prefix, "Other")


def strip_prefix(subject: str) -> str:
    """Remove the conventional-commit prefix from the subject for cleaner display."""
    match = re.match(r"^(\w+)(?:\(([^)]+)\))?:\s*(.+)$", subject)
    if match:
        return match.group(3)
    return subject


def render_section(version: str, commit_date: str, commits: list[tuple[str, str, str]]) -> str:
    """Render one version section."""
    if not commits:
        return ""

    by_category: dict[str, list[tuple[str, str]]] = {}
    for sha, subject, _ in commits:
        if should_skip(subject):
            continue
        cat = categorize(subject)
        by_category.setdefault(cat, []).append((sha, strip_prefix(subject)))

    if not by_category:
        return ""

    out = [f"## [{version}] — {commit_date}\n"]
    # Order categories logically
    order = ["Added", "Changed", "Fixed", "Removed", "Performance", "Documentation", "Testing", "CI/CD", "Build", "Maintenance", "Style", "Reverted", "Other"]
    for cat in order:
        if cat not in by_category:
            continue
        out.append(f"### {cat}\n")
        for sha, subject in by_category[cat]:
            out.append(f"- {subject} ({sha})")
        out.append("")
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--since", help="Generate from this version backwards")
    parser.add_argument("--output", default="CHANGELOG.md", help="Output file (default: CHANGELOG.md)")
    parser.add_argument("--unreleased-version", default="Unreleased", help="Label for unreleased commits")
    args = parser.parse_args()

    output_path = ROOT / args.output

    sections = [f"# Changelog\n\n_Generated by `tools/audit/changelog-generate.py` on {date.today().isoformat()}._\n"]

    tags = get_tags()
    if not tags:
        # No tags — all commits as "Unreleased"
        commits = get_commits_between(None)
        sections.append(render_section(args.unreleased_version, date.today().isoformat(), commits))
    else:
        # Unreleased = HEAD .. latest tag
        unreleased = get_commits_between(tags[0], "HEAD")
        if unreleased:
            sections.append(render_section(args.unreleased_version, date.today().isoformat(), unreleased))

        # Each tag-to-tag range
        for i, tag in enumerate(tags):
            prev_tag = tags[i + 1] if i + 1 < len(tags) else None
            commits = get_commits_between(prev_tag, tag)
            tag_date_out = run(["git", "log", "-1", "--pretty=format:%ad", "--date=short", tag]).strip()
            section = render_section(tag, tag_date_out, commits)
            if section:
                sections.append(section)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(s for s in sections if s) + "\n", encoding="utf-8")
    try:
        display_path = output_path.relative_to(ROOT)
    except ValueError:
        display_path = output_path
    print(f"Wrote {display_path}")


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as e:
        print(f"git command failed: {e.stderr}", file=sys.stderr)
        sys.exit(1)
